// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package qsc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Node                 int64    `protobuf:"varint,1,opt,name=node,proto3" json:"node,omitempty"`
	Proposal             *any.Any `protobuf:"bytes,2,opt,name=proposal,proto3" json:"proposal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetNode() int64 {
	if m != nil {
		return m.Node
	}
	return 0
}

func (m *Message) GetProposal() *any.Any {
	if m != nil {
		return m.Proposal
	}
	return nil
}

type MessageSet struct {
	Messages             map[int64]*Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	TimeStep             uint64             `protobuf:"varint,2,opt,name=timeStep,proto3" json:"timeStep,omitempty"`
	Node                 int64              `protobuf:"varint,3,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *MessageSet) Reset()         { *m = MessageSet{} }
func (m *MessageSet) String() string { return proto.CompactTextString(m) }
func (*MessageSet) ProtoMessage()    {}
func (*MessageSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *MessageSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageSet.Unmarshal(m, b)
}
func (m *MessageSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageSet.Marshal(b, m, deterministic)
}
func (m *MessageSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageSet.Merge(m, src)
}
func (m *MessageSet) XXX_Size() int {
	return xxx_messageInfo_MessageSet.Size(m)
}
func (m *MessageSet) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageSet.DiscardUnknown(m)
}

var xxx_messageInfo_MessageSet proto.InternalMessageInfo

func (m *MessageSet) GetMessages() map[int64]*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *MessageSet) GetTimeStep() uint64 {
	if m != nil {
		return m.TimeStep
	}
	return 0
}

func (m *MessageSet) GetNode() int64 {
	if m != nil {
		return m.Node
	}
	return 0
}

type View struct {
	Received             *MessageSet `protobuf:"bytes,1,opt,name=received,proto3" json:"received,omitempty"`
	Broadcasted          *MessageSet `protobuf:"bytes,2,opt,name=broadcasted,proto3" json:"broadcasted,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *View) Reset()         { *m = View{} }
func (m *View) String() string { return proto.CompactTextString(m) }
func (*View) ProtoMessage()    {}
func (*View) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2}
}

func (m *View) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_View.Unmarshal(m, b)
}
func (m *View) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_View.Marshal(b, m, deterministic)
}
func (m *View) XXX_Merge(src proto.Message) {
	xxx_messageInfo_View.Merge(m, src)
}
func (m *View) XXX_Size() int {
	return xxx_messageInfo_View.Size(m)
}
func (m *View) XXX_DiscardUnknown() {
	xxx_messageInfo_View.DiscardUnknown(m)
}

var xxx_messageInfo_View proto.InternalMessageInfo

func (m *View) GetReceived() *MessageSet {
	if m != nil {
		return m.Received
	}
	return nil
}

func (m *View) GetBroadcasted() *MessageSet {
	if m != nil {
		return m.Broadcasted
	}
	return nil
}

type RequestMessageSet struct {
	TimeStep             uint64   `protobuf:"varint,1,opt,name=timeStep,proto3" json:"timeStep,omitempty"`
	Nodes                []int64  `protobuf:"varint,2,rep,packed,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestMessageSet) Reset()         { *m = RequestMessageSet{} }
func (m *RequestMessageSet) String() string { return proto.CompactTextString(m) }
func (*RequestMessageSet) ProtoMessage()    {}
func (*RequestMessageSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{3}
}

func (m *RequestMessageSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestMessageSet.Unmarshal(m, b)
}
func (m *RequestMessageSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestMessageSet.Marshal(b, m, deterministic)
}
func (m *RequestMessageSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestMessageSet.Merge(m, src)
}
func (m *RequestMessageSet) XXX_Size() int {
	return xxx_messageInfo_RequestMessageSet.Size(m)
}
func (m *RequestMessageSet) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestMessageSet.DiscardUnknown(m)
}

var xxx_messageInfo_RequestMessageSet proto.InternalMessageInfo

func (m *RequestMessageSet) GetTimeStep() uint64 {
	if m != nil {
		return m.TimeStep
	}
	return 0
}

func (m *RequestMessageSet) GetNodes() []int64 {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "qsc.Message")
	proto.RegisterType((*MessageSet)(nil), "qsc.MessageSet")
	proto.RegisterMapType((map[int64]*Message)(nil), "qsc.MessageSet.MessagesEntry")
	proto.RegisterType((*View)(nil), "qsc.View")
	proto.RegisterType((*RequestMessageSet)(nil), "qsc.RequestMessageSet")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5) }

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 298 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x91, 0x4d, 0x4f, 0x83, 0x40,
	0x10, 0x86, 0x43, 0x97, 0x2a, 0x19, 0xfc, 0xdc, 0xf4, 0x50, 0x49, 0x4c, 0x0c, 0x27, 0x13, 0x93,
	0xad, 0xd6, 0x8b, 0x7a, 0xf3, 0xd0, 0x83, 0x07, 0x63, 0xb2, 0x4d, 0xbc, 0x2f, 0x30, 0x25, 0x44,
	0xca, 0x52, 0x76, 0xa9, 0xe1, 0xef, 0xf9, 0xcb, 0xdc, 0xf2, 0x55, 0x6c, 0xbc, 0xcd, 0xee, 0x3c,
	0x3c, 0xbc, 0x2f, 0xc0, 0xd9, 0x1a, 0x95, 0x12, 0x31, 0x2a, 0x96, 0x17, 0x52, 0x4b, 0x4a, 0x36,
	0x2a, 0xf4, 0xae, 0x62, 0x29, 0xe3, 0x14, 0x67, 0xf5, 0x55, 0x50, 0xae, 0x66, 0x22, 0xab, 0x9a,
	0xbd, 0xff, 0x01, 0xc7, 0xef, 0xcd, 0x13, 0x94, 0x82, 0x9d, 0xc9, 0x08, 0xa7, 0xd6, 0x8d, 0x75,
	0x4b, 0x78, 0x3d, 0xd3, 0x7b, 0x70, 0x0c, 0x97, 0x4b, 0x25, 0xd2, 0xe9, 0xc8, 0xdc, 0xbb, 0xf3,
	0x09, 0x6b, 0x64, 0xac, 0x93, 0xb1, 0xd7, 0xac, 0xe2, 0x3d, 0xe5, 0xff, 0x58, 0x00, 0xad, 0x71,
	0x89, 0x9a, 0x3e, 0x83, 0xd3, 0x25, 0x32, 0x62, 0x62, 0x04, 0xd7, 0xcc, 0x44, 0x62, 0x7b, 0xa4,
	0x1b, 0xd5, 0x22, 0xd3, 0x85, 0x31, 0x75, 0x38, 0xf5, 0xc0, 0xd1, 0xc9, 0x1a, 0x97, 0x1a, 0xf3,
	0xfa, 0xdd, 0x36, 0xef, 0xcf, 0x7d, 0x56, 0xb2, 0xcf, 0xea, 0xbd, 0xc1, 0xe9, 0x1f, 0x15, 0xbd,
	0x00, 0xf2, 0x85, 0x55, 0xdb, 0x67, 0x37, 0x52, 0x1f, 0xc6, 0x5b, 0x91, 0x96, 0xd8, 0x76, 0x39,
	0x19, 0x46, 0xe1, 0xcd, 0xea, 0x65, 0xf4, 0x64, 0xf9, 0x2b, 0xb0, 0x3f, 0x13, 0xfc, 0xa6, 0x77,
	0xe0, 0x14, 0x18, 0x62, 0xb2, 0xc5, 0xa8, 0xd6, 0xb8, 0xf3, 0xf3, 0x83, 0xf4, 0xbc, 0x07, 0xe8,
	0x03, 0xb8, 0x41, 0x21, 0x45, 0x14, 0x0a, 0xa5, 0x0d, 0x3f, 0xfa, 0x9f, 0x1f, 0x32, 0xfe, 0x02,
	0x2e, 0x39, 0x6e, 0x4a, 0x54, 0x7a, 0xf0, 0xc9, 0x86, 0xbd, 0xad, 0x83, 0xde, 0x13, 0x18, 0xef,
	0xba, 0x2a, 0x63, 0x27, 0xa6, 0x54, 0x73, 0x08, 0x8e, 0xea, 0x7f, 0xf1, 0xf8, 0x1b, 0x00, 0x00,
	0xff, 0xff, 0xef, 0x50, 0x9a, 0x81, 0xfd, 0x01, 0x00, 0x00,
}
