// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package contract

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Instance struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                *any.Any `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	ContractID           string   `protobuf:"bytes,3,opt,name=contractID,proto3" json:"contractID,omitempty"`
	Deleted              bool     `protobuf:"varint,4,opt,name=deleted,proto3" json:"deleted,omitempty"`
	AccessControl        []byte   `protobuf:"bytes,5,opt,name=accessControl,proto3" json:"accessControl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Instance) Reset()         { *m = Instance{} }
func (m *Instance) String() string { return proto.CompactTextString(m) }
func (*Instance) ProtoMessage()    {}
func (*Instance) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *Instance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Instance.Unmarshal(m, b)
}
func (m *Instance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Instance.Marshal(b, m, deterministic)
}
func (m *Instance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Instance.Merge(m, src)
}
func (m *Instance) XXX_Size() int {
	return xxx_messageInfo_Instance.Size(m)
}
func (m *Instance) XXX_DiscardUnknown() {
	xxx_messageInfo_Instance.DiscardUnknown(m)
}

var xxx_messageInfo_Instance proto.InternalMessageInfo

func (m *Instance) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Instance) GetValue() *any.Any {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Instance) GetContractID() string {
	if m != nil {
		return m.ContractID
	}
	return ""
}

func (m *Instance) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func (m *Instance) GetAccessControl() []byte {
	if m != nil {
		return m.AccessControl
	}
	return nil
}

type SpawnTaskProto struct {
	ContractID           string   `protobuf:"bytes,1,opt,name=contractID,proto3" json:"contractID,omitempty"`
	Argument             *any.Any `protobuf:"bytes,2,opt,name=argument,proto3" json:"argument,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpawnTaskProto) Reset()         { *m = SpawnTaskProto{} }
func (m *SpawnTaskProto) String() string { return proto.CompactTextString(m) }
func (*SpawnTaskProto) ProtoMessage()    {}
func (*SpawnTaskProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *SpawnTaskProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpawnTaskProto.Unmarshal(m, b)
}
func (m *SpawnTaskProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpawnTaskProto.Marshal(b, m, deterministic)
}
func (m *SpawnTaskProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpawnTaskProto.Merge(m, src)
}
func (m *SpawnTaskProto) XXX_Size() int {
	return xxx_messageInfo_SpawnTaskProto.Size(m)
}
func (m *SpawnTaskProto) XXX_DiscardUnknown() {
	xxx_messageInfo_SpawnTaskProto.DiscardUnknown(m)
}

var xxx_messageInfo_SpawnTaskProto proto.InternalMessageInfo

func (m *SpawnTaskProto) GetContractID() string {
	if m != nil {
		return m.ContractID
	}
	return ""
}

func (m *SpawnTaskProto) GetArgument() *any.Any {
	if m != nil {
		return m.Argument
	}
	return nil
}

type InvokeTaskProto struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Argument             *any.Any `protobuf:"bytes,2,opt,name=argument,proto3" json:"argument,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvokeTaskProto) Reset()         { *m = InvokeTaskProto{} }
func (m *InvokeTaskProto) String() string { return proto.CompactTextString(m) }
func (*InvokeTaskProto) ProtoMessage()    {}
func (*InvokeTaskProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2}
}

func (m *InvokeTaskProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvokeTaskProto.Unmarshal(m, b)
}
func (m *InvokeTaskProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvokeTaskProto.Marshal(b, m, deterministic)
}
func (m *InvokeTaskProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvokeTaskProto.Merge(m, src)
}
func (m *InvokeTaskProto) XXX_Size() int {
	return xxx_messageInfo_InvokeTaskProto.Size(m)
}
func (m *InvokeTaskProto) XXX_DiscardUnknown() {
	xxx_messageInfo_InvokeTaskProto.DiscardUnknown(m)
}

var xxx_messageInfo_InvokeTaskProto proto.InternalMessageInfo

func (m *InvokeTaskProto) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *InvokeTaskProto) GetArgument() *any.Any {
	if m != nil {
		return m.Argument
	}
	return nil
}

type DeleteTaskProto struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTaskProto) Reset()         { *m = DeleteTaskProto{} }
func (m *DeleteTaskProto) String() string { return proto.CompactTextString(m) }
func (*DeleteTaskProto) ProtoMessage()    {}
func (*DeleteTaskProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{3}
}

func (m *DeleteTaskProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTaskProto.Unmarshal(m, b)
}
func (m *DeleteTaskProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTaskProto.Marshal(b, m, deterministic)
}
func (m *DeleteTaskProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTaskProto.Merge(m, src)
}
func (m *DeleteTaskProto) XXX_Size() int {
	return xxx_messageInfo_DeleteTaskProto.Size(m)
}
func (m *DeleteTaskProto) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTaskProto.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTaskProto proto.InternalMessageInfo

func (m *DeleteTaskProto) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func init() {
	proto.RegisterType((*Instance)(nil), "contract.Instance")
	proto.RegisterType((*SpawnTaskProto)(nil), "contract.SpawnTaskProto")
	proto.RegisterType((*InvokeTaskProto)(nil), "contract.InvokeTaskProto")
	proto.RegisterType((*DeleteTaskProto)(nil), "contract.DeleteTaskProto")
}

func init() {
	proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5)
}

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x59, 0x6b, 0x35, 0x8e, 0xda, 0xca, 0xe2, 0x61, 0xf5, 0x20, 0x21, 0x7a, 0x08, 0x1e,
	0x52, 0xd1, 0x27, 0x10, 0x7b, 0xc9, 0x4d, 0xa2, 0x3e, 0xc0, 0x64, 0x3b, 0xe6, 0x90, 0x74, 0xb6,
	0x64, 0x37, 0x95, 0xbc, 0x91, 0x8f, 0x29, 0xdd, 0x10, 0xb5, 0x14, 0x02, 0xbd, 0xed, 0xfe, 0xfc,
	0xf3, 0x7f, 0xf3, 0x0f, 0x4c, 0x96, 0x64, 0x2d, 0x16, 0x64, 0x93, 0x55, 0x6d, 0x9c, 0x91, 0x81,
	0x36, 0xec, 0x6a, 0xd4, 0xee, 0xfa, 0xaa, 0x30, 0xa6, 0xa8, 0x68, 0xe6, 0xf5, 0xbc, 0xf9, 0x9c,
	0x21, 0xb7, 0x9d, 0x29, 0xfa, 0x16, 0x10, 0xa4, 0x6c, 0x1d, 0xb2, 0x26, 0x79, 0x01, 0xa3, 0x92,
	0x5a, 0x25, 0x42, 0x11, 0x9f, 0x65, 0x9b, 0xa7, 0xbc, 0x87, 0xf1, 0x1a, 0xab, 0x86, 0xd4, 0x41,
	0x28, 0xe2, 0xd3, 0xc7, 0xcb, 0xa4, 0x4b, 0x4a, 0xfa, 0xa4, 0xe4, 0x99, 0xdb, 0xac, 0xb3, 0xc8,
	0x1b, 0x80, 0x9e, 0x98, 0xce, 0xd5, 0x28, 0x14, 0xf1, 0x49, 0xf6, 0x4f, 0x91, 0x0a, 0x8e, 0x17,
	0x54, 0x91, 0xa3, 0x85, 0x3a, 0x0c, 0x45, 0x1c, 0x64, 0xfd, 0x57, 0xde, 0xc1, 0x39, 0x6a, 0x4d,
	0xd6, 0xbe, 0x6c, 0xdc, 0xa6, 0x52, 0x63, 0xbf, 0xc1, 0xb6, 0x18, 0xe5, 0x30, 0x79, 0x5b, 0xe1,
	0x17, 0xbf, 0xa3, 0x2d, 0x5f, 0x7d, 0xc3, 0x6d, 0xa2, 0xd8, 0x21, 0x3e, 0x40, 0x80, 0x75, 0xd1,
	0x2c, 0x89, 0xdd, 0x60, 0x81, 0x5f, 0x57, 0xf4, 0x01, 0xd3, 0x94, 0xd7, 0xa6, 0xa4, 0x3f, 0xc8,
	0xee, 0x51, 0xf6, 0x8f, 0xbd, 0x85, 0xe9, 0xdc, 0x77, 0x1d, 0x88, 0xcd, 0x8f, 0xfc, 0xf0, 0xd3,
	0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc8, 0x88, 0xcd, 0x32, 0xc8, 0x01, 0x00, 0x00,
}
