// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package cosipbft

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ForwardLinkProto struct {
	From                 []byte   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   []byte   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Prepare              *any.Any `protobuf:"bytes,3,opt,name=prepare,proto3" json:"prepare,omitempty"`
	Commit               *any.Any `protobuf:"bytes,4,opt,name=commit,proto3" json:"commit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForwardLinkProto) Reset()         { *m = ForwardLinkProto{} }
func (m *ForwardLinkProto) String() string { return proto.CompactTextString(m) }
func (*ForwardLinkProto) ProtoMessage()    {}
func (*ForwardLinkProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *ForwardLinkProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForwardLinkProto.Unmarshal(m, b)
}
func (m *ForwardLinkProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForwardLinkProto.Marshal(b, m, deterministic)
}
func (m *ForwardLinkProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForwardLinkProto.Merge(m, src)
}
func (m *ForwardLinkProto) XXX_Size() int {
	return xxx_messageInfo_ForwardLinkProto.Size(m)
}
func (m *ForwardLinkProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ForwardLinkProto.DiscardUnknown(m)
}

var xxx_messageInfo_ForwardLinkProto proto.InternalMessageInfo

func (m *ForwardLinkProto) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *ForwardLinkProto) GetTo() []byte {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *ForwardLinkProto) GetPrepare() *any.Any {
	if m != nil {
		return m.Prepare
	}
	return nil
}

func (m *ForwardLinkProto) GetCommit() *any.Any {
	if m != nil {
		return m.Commit
	}
	return nil
}

type ChainProto struct {
	Links                []*ForwardLinkProto `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ChainProto) Reset()         { *m = ChainProto{} }
func (m *ChainProto) String() string { return proto.CompactTextString(m) }
func (*ChainProto) ProtoMessage()    {}
func (*ChainProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *ChainProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainProto.Unmarshal(m, b)
}
func (m *ChainProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainProto.Marshal(b, m, deterministic)
}
func (m *ChainProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainProto.Merge(m, src)
}
func (m *ChainProto) XXX_Size() int {
	return xxx_messageInfo_ChainProto.Size(m)
}
func (m *ChainProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainProto.DiscardUnknown(m)
}

var xxx_messageInfo_ChainProto proto.InternalMessageInfo

func (m *ChainProto) GetLinks() []*ForwardLinkProto {
	if m != nil {
		return m.Links
	}
	return nil
}

type Prepare struct {
	Proposal             *any.Any `protobuf:"bytes,1,opt,name=proposal,proto3" json:"proposal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Prepare) Reset()         { *m = Prepare{} }
func (m *Prepare) String() string { return proto.CompactTextString(m) }
func (*Prepare) ProtoMessage()    {}
func (*Prepare) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2}
}

func (m *Prepare) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Prepare.Unmarshal(m, b)
}
func (m *Prepare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Prepare.Marshal(b, m, deterministic)
}
func (m *Prepare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Prepare.Merge(m, src)
}
func (m *Prepare) XXX_Size() int {
	return xxx_messageInfo_Prepare.Size(m)
}
func (m *Prepare) XXX_DiscardUnknown() {
	xxx_messageInfo_Prepare.DiscardUnknown(m)
}

var xxx_messageInfo_Prepare proto.InternalMessageInfo

func (m *Prepare) GetProposal() *any.Any {
	if m != nil {
		return m.Proposal
	}
	return nil
}

type Commit struct {
	ForwardLink          *ForwardLinkProto `protobuf:"bytes,1,opt,name=forwardLink,proto3" json:"forwardLink,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Commit) Reset()         { *m = Commit{} }
func (m *Commit) String() string { return proto.CompactTextString(m) }
func (*Commit) ProtoMessage()    {}
func (*Commit) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{3}
}

func (m *Commit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Commit.Unmarshal(m, b)
}
func (m *Commit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Commit.Marshal(b, m, deterministic)
}
func (m *Commit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Commit.Merge(m, src)
}
func (m *Commit) XXX_Size() int {
	return xxx_messageInfo_Commit.Size(m)
}
func (m *Commit) XXX_DiscardUnknown() {
	xxx_messageInfo_Commit.DiscardUnknown(m)
}

var xxx_messageInfo_Commit proto.InternalMessageInfo

func (m *Commit) GetForwardLink() *ForwardLinkProto {
	if m != nil {
		return m.ForwardLink
	}
	return nil
}

type Propagate struct {
	ForwardLink          *ForwardLinkProto `protobuf:"bytes,1,opt,name=forwardLink,proto3" json:"forwardLink,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Propagate) Reset()         { *m = Propagate{} }
func (m *Propagate) String() string { return proto.CompactTextString(m) }
func (*Propagate) ProtoMessage()    {}
func (*Propagate) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{4}
}

func (m *Propagate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Propagate.Unmarshal(m, b)
}
func (m *Propagate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Propagate.Marshal(b, m, deterministic)
}
func (m *Propagate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Propagate.Merge(m, src)
}
func (m *Propagate) XXX_Size() int {
	return xxx_messageInfo_Propagate.Size(m)
}
func (m *Propagate) XXX_DiscardUnknown() {
	xxx_messageInfo_Propagate.DiscardUnknown(m)
}

var xxx_messageInfo_Propagate proto.InternalMessageInfo

func (m *Propagate) GetForwardLink() *ForwardLinkProto {
	if m != nil {
		return m.ForwardLink
	}
	return nil
}

func init() {
	proto.RegisterType((*ForwardLinkProto)(nil), "cosipbft.ForwardLinkProto")
	proto.RegisterType((*ChainProto)(nil), "cosipbft.ChainProto")
	proto.RegisterType((*Prepare)(nil), "cosipbft.Prepare")
	proto.RegisterType((*Commit)(nil), "cosipbft.Commit")
	proto.RegisterType((*Propagate)(nil), "cosipbft.Propagate")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5) }

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x8f, 0x41, 0x4b, 0xc3, 0x30,
	0x18, 0x86, 0xe9, 0x36, 0xbb, 0xf9, 0x4d, 0x86, 0x04, 0x0f, 0x75, 0x27, 0xc9, 0xc9, 0x83, 0x64,
	0x43, 0x8f, 0x8a, 0x20, 0x83, 0x81, 0xe0, 0x61, 0xf4, 0x1f, 0x7c, 0x9d, 0x69, 0x2d, 0xb6, 0xf9,
	0x42, 0x12, 0x91, 0xfd, 0x0f, 0x7f, 0xb0, 0x21, 0x69, 0x55, 0x04, 0x7b, 0xf1, 0x16, 0x5e, 0x9e,
	0x37, 0xcf, 0xfb, 0xc1, 0xa2, 0x95, 0xd6, 0x62, 0x25, 0xad, 0xd0, 0x86, 0x1c, 0xb1, 0xd9, 0x9e,
	0x6c, 0xad, 0x8b, 0xd2, 0x2d, 0xcf, 0x2b, 0xa2, 0xaa, 0x91, 0xab, 0x90, 0x17, 0x6f, 0xe5, 0x0a,
	0xd5, 0x21, 0x42, 0xfc, 0x23, 0x81, 0xd3, 0x2d, 0x99, 0x77, 0x34, 0xcf, 0x4f, 0xb5, 0x7a, 0xdd,
	0x85, 0x26, 0x83, 0x49, 0x69, 0xa8, 0xcd, 0x92, 0x8b, 0xe4, 0xf2, 0x24, 0x0f, 0x6f, 0xb6, 0x80,
	0x91, 0xa3, 0x6c, 0x14, 0x12, 0xff, 0x62, 0x02, 0xa6, 0xda, 0x48, 0x8d, 0x46, 0x66, 0x63, 0x1f,
	0xce, 0xaf, 0xcf, 0x44, 0xb4, 0x88, 0xde, 0x22, 0x1e, 0xd4, 0x21, 0xef, 0x21, 0x76, 0x05, 0xe9,
	0x9e, 0xda, 0xb6, 0x76, 0xd9, 0x64, 0x00, 0xef, 0x18, 0x7e, 0x0f, 0xb0, 0x79, 0xc1, 0x5a, 0xc5,
	0x3d, 0x6b, 0x38, 0x6a, 0xfc, 0x38, 0xeb, 0x07, 0x8d, 0x7d, 0x75, 0x29, 0xfa, 0xcb, 0xc4, 0xef,
	0xe9, 0x79, 0x04, 0xf9, 0x2d, 0x4c, 0x77, 0x9d, 0x78, 0x0d, 0x33, 0xaf, 0xd0, 0x64, 0xb1, 0x09,
	0x07, 0xfd, 0xa5, 0xfe, 0xa2, 0xf8, 0x16, 0xd2, 0x4d, 0x98, 0xc1, 0xee, 0x60, 0x5e, 0x7e, 0x1b,
	0xba, 0xfa, 0x90, 0xfe, 0x27, 0xce, 0x1f, 0xe1, 0xd8, 0xa7, 0x1a, 0x2b, 0x74, 0xf2, 0x7f, 0x5f,
	0x15, 0x69, 0x98, 0x7a, 0xf3, 0x19, 0x00, 0x00, 0xff, 0xff, 0xa4, 0xac, 0xe1, 0x0d, 0xe4, 0x01,
	0x00, 0x00,
}
