// Code generated by protoc-gen-go. DO NOT EDIT.
// source: overlay.proto

package minogrpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	From                 []byte   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Payload              *any.Any `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_61fc82527fbe24ad, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Message) GetPayload() *any.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

// Envelope is wrapper around a message and one or several recipients.
type Envelope struct {
	To                   [][]byte `protobuf:"bytes,1,rep,name=to,proto3" json:"to,omitempty"`
	Message              *Message `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Envelope) Reset()         { *m = Envelope{} }
func (m *Envelope) String() string { return proto.CompactTextString(m) }
func (*Envelope) ProtoMessage()    {}
func (*Envelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_61fc82527fbe24ad, []int{1}
}

func (m *Envelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Envelope.Unmarshal(m, b)
}
func (m *Envelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Envelope.Marshal(b, m, deterministic)
}
func (m *Envelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Envelope.Merge(m, src)
}
func (m *Envelope) XXX_Size() int {
	return xxx_messageInfo_Envelope.Size(m)
}
func (m *Envelope) XXX_DiscardUnknown() {
	xxx_messageInfo_Envelope.DiscardUnknown(m)
}

var xxx_messageInfo_Envelope proto.InternalMessageInfo

func (m *Envelope) GetTo() [][]byte {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Envelope) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "minogrpc.Message")
	proto.RegisterType((*Envelope)(nil), "minogrpc.Envelope")
}

func init() {
	proto.RegisterFile("overlay.proto", fileDescriptor_61fc82527fbe24ad)
}

var fileDescriptor_61fc82527fbe24ad = []byte{
	// 223 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0x37, 0x75, 0xb5, 0xcb, 0xb8, 0x0a, 0x0e, 0x1e, 0x6a, 0x4f, 0x25, 0xa7, 0x80, 0x30,
	0x2b, 0x2b, 0xfe, 0x00, 0x11, 0xf1, 0xb4, 0x08, 0xf9, 0x07, 0x59, 0xcd, 0x06, 0x21, 0xcd, 0x84,
	0x6c, 0x5d, 0xe8, 0xbf, 0x17, 0xdb, 0x06, 0x0f, 0xf5, 0x36, 0xbc, 0xf9, 0xe6, 0xcd, 0x7b, 0x70,
	0xc5, 0x27, 0x9b, 0xbc, 0xe9, 0x29, 0x26, 0xee, 0x18, 0x57, 0xed, 0x57, 0x60, 0x97, 0xe2, 0x47,
	0x7d, 0xe7, 0x98, 0x9d, 0xb7, 0x9b, 0x41, 0xdf, 0x7f, 0x1f, 0x36, 0x26, 0x4c, 0x90, 0xdc, 0x41,
	0xb9, 0xb3, 0xc7, 0xa3, 0x71, 0x16, 0x11, 0x96, 0x87, 0xc4, 0x6d, 0x25, 0x1a, 0xa1, 0xd6, 0x7a,
	0x98, 0x91, 0xa0, 0x8c, 0xa6, 0xf7, 0x6c, 0x3e, 0xab, 0xa2, 0x11, 0xea, 0x72, 0x7b, 0x4b, 0xa3,
	0x17, 0x65, 0x2f, 0x7a, 0x0e, 0xbd, 0xce, 0x90, 0x7c, 0x83, 0xd5, 0x6b, 0x38, 0x59, 0xcf, 0xd1,
	0xe2, 0x35, 0x14, 0x1d, 0x57, 0xa2, 0x39, 0x53, 0x6b, 0x5d, 0x74, 0x8c, 0xf7, 0x50, 0xb6, 0xe3,
	0xab, 0xc9, 0xeb, 0x86, 0x72, 0x42, 0x9a, 0x32, 0xe8, 0x4c, 0x6c, 0x23, 0x94, 0xef, 0x63, 0x1b,
	0x24, 0x58, 0xbe, 0x18, 0xef, 0x71, 0x8e, 0xd7, 0x73, 0x49, 0x2e, 0xf0, 0x09, 0xce, 0xb5, 0xfd,
	0x3d, 0xc4, 0xbf, 0x6d, 0x0e, 0x55, 0xff, 0xa3, 0xc9, 0x85, 0x12, 0x0f, 0x62, 0x7f, 0x31, 0x34,
	0x7a, 0xfc, 0x09, 0x00, 0x00, 0xff, 0xff, 0x50, 0x50, 0xe3, 0x1e, 0x46, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OverlayClient is the client API for Overlay service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OverlayClient interface {
	Call(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
	Relay(ctx context.Context, opts ...grpc.CallOption) (Overlay_RelayClient, error)
}

type overlayClient struct {
	cc grpc.ClientConnInterface
}

func NewOverlayClient(cc grpc.ClientConnInterface) OverlayClient {
	return &overlayClient{cc}
}

func (c *overlayClient) Call(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/minogrpc.Overlay/Call", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *overlayClient) Relay(ctx context.Context, opts ...grpc.CallOption) (Overlay_RelayClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Overlay_serviceDesc.Streams[0], "/minogrpc.Overlay/Relay", opts...)
	if err != nil {
		return nil, err
	}
	x := &overlayRelayClient{stream}
	return x, nil
}

type Overlay_RelayClient interface {
	Send(*Envelope) error
	Recv() (*Envelope, error)
	grpc.ClientStream
}

type overlayRelayClient struct {
	grpc.ClientStream
}

func (x *overlayRelayClient) Send(m *Envelope) error {
	return x.ClientStream.SendMsg(m)
}

func (x *overlayRelayClient) Recv() (*Envelope, error) {
	m := new(Envelope)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// OverlayServer is the server API for Overlay service.
type OverlayServer interface {
	Call(context.Context, *Message) (*Message, error)
	Relay(Overlay_RelayServer) error
}

// UnimplementedOverlayServer can be embedded to have forward compatible implementations.
type UnimplementedOverlayServer struct {
}

func (*UnimplementedOverlayServer) Call(ctx context.Context, req *Message) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Call not implemented")
}
func (*UnimplementedOverlayServer) Relay(srv Overlay_RelayServer) error {
	return status.Errorf(codes.Unimplemented, "method Relay not implemented")
}

func RegisterOverlayServer(s *grpc.Server, srv OverlayServer) {
	s.RegisterService(&_Overlay_serviceDesc, srv)
}

func _Overlay_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OverlayServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/minogrpc.Overlay/Call",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OverlayServer).Call(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _Overlay_Relay_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OverlayServer).Relay(&overlayRelayServer{stream})
}

type Overlay_RelayServer interface {
	Send(*Envelope) error
	Recv() (*Envelope, error)
	grpc.ServerStream
}

type overlayRelayServer struct {
	grpc.ServerStream
}

func (x *overlayRelayServer) Send(m *Envelope) error {
	return x.ServerStream.SendMsg(m)
}

func (x *overlayRelayServer) Recv() (*Envelope, error) {
	m := new(Envelope)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Overlay_serviceDesc = grpc.ServiceDesc{
	ServiceName: "minogrpc.Overlay",
	HandlerType: (*OverlayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _Overlay_Call_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Relay",
			Handler:       _Overlay_Relay_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "overlay.proto",
}
