// Code generated by protoc-gen-go. DO NOT EDIT.
// source: overlay.proto

package minogrpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Envelope is wrapper around a message and one or several recipients.
type Envelope struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   []string `protobuf:"bytes,2,rep,name=to,proto3" json:"to,omitempty"`
	Message              *any.Any `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Envelope) Reset()         { *m = Envelope{} }
func (m *Envelope) String() string { return proto.CompactTextString(m) }
func (*Envelope) ProtoMessage()    {}
func (*Envelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_61fc82527fbe24ad, []int{0}
}

func (m *Envelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Envelope.Unmarshal(m, b)
}
func (m *Envelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Envelope.Marshal(b, m, deterministic)
}
func (m *Envelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Envelope.Merge(m, src)
}
func (m *Envelope) XXX_Size() int {
	return xxx_messageInfo_Envelope.Size(m)
}
func (m *Envelope) XXX_DiscardUnknown() {
	xxx_messageInfo_Envelope.DiscardUnknown(m)
}

var xxx_messageInfo_Envelope proto.InternalMessageInfo

func (m *Envelope) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Envelope) GetTo() []string {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Envelope) GetMessage() *any.Any {
	if m != nil {
		return m.Message
	}
	return nil
}

type OverlayMsg struct {
	Message              *any.Any `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OverlayMsg) Reset()         { *m = OverlayMsg{} }
func (m *OverlayMsg) String() string { return proto.CompactTextString(m) }
func (*OverlayMsg) ProtoMessage()    {}
func (*OverlayMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_61fc82527fbe24ad, []int{1}
}

func (m *OverlayMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OverlayMsg.Unmarshal(m, b)
}
func (m *OverlayMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OverlayMsg.Marshal(b, m, deterministic)
}
func (m *OverlayMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OverlayMsg.Merge(m, src)
}
func (m *OverlayMsg) XXX_Size() int {
	return xxx_messageInfo_OverlayMsg.Size(m)
}
func (m *OverlayMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_OverlayMsg.DiscardUnknown(m)
}

var xxx_messageInfo_OverlayMsg proto.InternalMessageInfo

func (m *OverlayMsg) GetMessage() *any.Any {
	if m != nil {
		return m.Message
	}
	return nil
}

type RoutingMsg struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Addrs                []string `protobuf:"bytes,2,rep,name=addrs,proto3" json:"addrs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoutingMsg) Reset()         { *m = RoutingMsg{} }
func (m *RoutingMsg) String() string { return proto.CompactTextString(m) }
func (*RoutingMsg) ProtoMessage()    {}
func (*RoutingMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_61fc82527fbe24ad, []int{2}
}

func (m *RoutingMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoutingMsg.Unmarshal(m, b)
}
func (m *RoutingMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoutingMsg.Marshal(b, m, deterministic)
}
func (m *RoutingMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoutingMsg.Merge(m, src)
}
func (m *RoutingMsg) XXX_Size() int {
	return xxx_messageInfo_RoutingMsg.Size(m)
}
func (m *RoutingMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_RoutingMsg.DiscardUnknown(m)
}

var xxx_messageInfo_RoutingMsg proto.InternalMessageInfo

func (m *RoutingMsg) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *RoutingMsg) GetAddrs() []string {
	if m != nil {
		return m.Addrs
	}
	return nil
}

func init() {
	proto.RegisterType((*Envelope)(nil), "minogrpc.Envelope")
	proto.RegisterType((*OverlayMsg)(nil), "minogrpc.OverlayMsg")
	proto.RegisterType((*RoutingMsg)(nil), "minogrpc.RoutingMsg")
}

func init() { proto.RegisterFile("overlay.proto", fileDescriptor_61fc82527fbe24ad) }

var fileDescriptor_61fc82527fbe24ad = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x86, 0x71, 0x1a, 0xfa, 0x71, 0x08, 0x86, 0x53, 0x86, 0xd0, 0x29, 0xca, 0x94, 0xc9, 0x45,
	0x05, 0x31, 0x20, 0x16, 0x84, 0x18, 0x11, 0x52, 0xd8, 0x91, 0x5c, 0x7a, 0xb5, 0x2a, 0x39, 0xbe,
	0xc8, 0x71, 0x2b, 0x45, 0xfc, 0x79, 0x94, 0x0f, 0x0b, 0x06, 0x06, 0xba, 0x9d, 0x4f, 0xef, 0xf3,
	0xfa, 0xb1, 0xe1, 0x92, 0x8f, 0xe4, 0x8c, 0x6a, 0x65, 0xed, 0xd8, 0x33, 0xce, 0xab, 0xbd, 0x65,
	0xed, 0xea, 0xcf, 0xe5, 0xb5, 0x66, 0xd6, 0x86, 0x56, 0xfd, 0x7e, 0x73, 0xd8, 0xad, 0x94, 0x1d,
	0x43, 0xf9, 0x07, 0xcc, 0x5f, 0xec, 0x91, 0x0c, 0xd7, 0x84, 0x08, 0xf1, 0xce, 0x71, 0x95, 0x8a,
	0x4c, 0x14, 0x8b, 0xb2, 0x9f, 0xf1, 0x0a, 0x22, 0xcf, 0x69, 0x94, 0x4d, 0x8a, 0x45, 0x19, 0x79,
	0x46, 0x09, 0xb3, 0x8a, 0x9a, 0x46, 0x69, 0x4a, 0x27, 0x99, 0x28, 0x2e, 0xd6, 0x89, 0x1c, 0xca,
	0x65, 0x28, 0x97, 0x4f, 0xb6, 0x2d, 0x43, 0x28, 0x7f, 0x04, 0x78, 0x1b, 0xac, 0x5e, 0x1b, 0xfd,
	0x9b, 0x16, 0xff, 0xa1, 0xef, 0x01, 0x4a, 0x3e, 0xf8, 0xbd, 0xd5, 0x1d, 0x8d, 0x10, 0xfb, 0xb6,
	0xa6, 0xe0, 0xd7, 0xcd, 0x98, 0xc0, 0xb9, 0xda, 0x6e, 0x5d, 0x33, 0x2a, 0x0e, 0x87, 0xf5, 0x17,
	0xcc, 0xc6, 0x5b, 0xf1, 0x0e, 0xe2, 0x67, 0x65, 0x0c, 0x26, 0x32, 0x7c, 0x87, 0xfc, 0x11, 0x5a,
	0xfe, 0xb9, 0xcd, 0xcf, 0xf0, 0x01, 0xa6, 0xef, 0xde, 0x91, 0xaa, 0x4e, 0xe3, 0x0a, 0x71, 0x23,
	0x36, 0xd3, 0xfe, 0x2d, 0xb7, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc2, 0xa9, 0x82, 0x7e, 0x8f,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OverlayClient is the client API for Overlay service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OverlayClient interface {
	Call(ctx context.Context, in *OverlayMsg, opts ...grpc.CallOption) (*OverlayMsg, error)
	Stream(ctx context.Context, opts ...grpc.CallOption) (Overlay_StreamClient, error)
}

type overlayClient struct {
	cc *grpc.ClientConn
}

func NewOverlayClient(cc *grpc.ClientConn) OverlayClient {
	return &overlayClient{cc}
}

func (c *overlayClient) Call(ctx context.Context, in *OverlayMsg, opts ...grpc.CallOption) (*OverlayMsg, error) {
	out := new(OverlayMsg)
	err := c.cc.Invoke(ctx, "/minogrpc.Overlay/Call", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *overlayClient) Stream(ctx context.Context, opts ...grpc.CallOption) (Overlay_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Overlay_serviceDesc.Streams[0], "/minogrpc.Overlay/Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &overlayStreamClient{stream}
	return x, nil
}

type Overlay_StreamClient interface {
	Send(*OverlayMsg) error
	Recv() (*OverlayMsg, error)
	grpc.ClientStream
}

type overlayStreamClient struct {
	grpc.ClientStream
}

func (x *overlayStreamClient) Send(m *OverlayMsg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *overlayStreamClient) Recv() (*OverlayMsg, error) {
	m := new(OverlayMsg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// OverlayServer is the server API for Overlay service.
type OverlayServer interface {
	Call(context.Context, *OverlayMsg) (*OverlayMsg, error)
	Stream(Overlay_StreamServer) error
}

// UnimplementedOverlayServer can be embedded to have forward compatible implementations.
type UnimplementedOverlayServer struct {
}

func (*UnimplementedOverlayServer) Call(ctx context.Context, req *OverlayMsg) (*OverlayMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Call not implemented")
}
func (*UnimplementedOverlayServer) Stream(srv Overlay_StreamServer) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}

func RegisterOverlayServer(s *grpc.Server, srv OverlayServer) {
	s.RegisterService(&_Overlay_serviceDesc, srv)
}

func _Overlay_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OverlayMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OverlayServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/minogrpc.Overlay/Call",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OverlayServer).Call(ctx, req.(*OverlayMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Overlay_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OverlayServer).Stream(&overlayStreamServer{stream})
}

type Overlay_StreamServer interface {
	Send(*OverlayMsg) error
	Recv() (*OverlayMsg, error)
	grpc.ServerStream
}

type overlayStreamServer struct {
	grpc.ServerStream
}

func (x *overlayStreamServer) Send(m *OverlayMsg) error {
	return x.ServerStream.SendMsg(m)
}

func (x *overlayStreamServer) Recv() (*OverlayMsg, error) {
	m := new(OverlayMsg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Overlay_serviceDesc = grpc.ServiceDesc{
	ServiceName: "minogrpc.Overlay",
	HandlerType: (*OverlayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _Overlay_Call_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _Overlay_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "overlay.proto",
}
