// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package pedersen

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// This is the message the initiator of the DKG protocol should send to all the
// nodes.
type Start struct {
	// threshold
	T uint32 `protobuf:"varint,1,opt,name=t,proto3" json:"t,omitempty"`
	// the full list of addresses that will participate in the DKG
	Addresses [][]byte `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	// the corresponding kyber.Point pub keys of the addresses
	PubKeys              [][]byte `protobuf:"bytes,3,rep,name=pubKeys,proto3" json:"pubKeys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Start) Reset()         { *m = Start{} }
func (m *Start) String() string { return proto.CompactTextString(m) }
func (*Start) ProtoMessage()    {}
func (*Start) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *Start) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Start.Unmarshal(m, b)
}
func (m *Start) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Start.Marshal(b, m, deterministic)
}
func (m *Start) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Start.Merge(m, src)
}
func (m *Start) XXX_Size() int {
	return xxx_messageInfo_Start.Size(m)
}
func (m *Start) XXX_DiscardUnknown() {
	xxx_messageInfo_Start.DiscardUnknown(m)
}

var xxx_messageInfo_Start proto.InternalMessageInfo

func (m *Start) GetT() uint32 {
	if m != nil {
		return m.T
	}
	return 0
}

func (m *Start) GetAddresses() [][]byte {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *Start) GetPubKeys() [][]byte {
	if m != nil {
		return m.PubKeys
	}
	return nil
}

// Matches the attributes defined in kyber dkg.Deal
type Deal struct {
	Index                uint32              `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	EncryptedDeal        *Deal_EncryptedDeal `protobuf:"bytes,2,opt,name=encryptedDeal,proto3" json:"encryptedDeal,omitempty"`
	Signature            []byte              `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Deal) Reset()         { *m = Deal{} }
func (m *Deal) String() string { return proto.CompactTextString(m) }
func (*Deal) ProtoMessage()    {}
func (*Deal) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *Deal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Deal.Unmarshal(m, b)
}
func (m *Deal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Deal.Marshal(b, m, deterministic)
}
func (m *Deal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Deal.Merge(m, src)
}
func (m *Deal) XXX_Size() int {
	return xxx_messageInfo_Deal.Size(m)
}
func (m *Deal) XXX_DiscardUnknown() {
	xxx_messageInfo_Deal.DiscardUnknown(m)
}

var xxx_messageInfo_Deal proto.InternalMessageInfo

func (m *Deal) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Deal) GetEncryptedDeal() *Deal_EncryptedDeal {
	if m != nil {
		return m.EncryptedDeal
	}
	return nil
}

func (m *Deal) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Deal_EncryptedDeal struct {
	Dhkey                []byte   `protobuf:"bytes,1,opt,name=dhkey,proto3" json:"dhkey,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Nonce                []byte   `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Cipher               []byte   `protobuf:"bytes,4,opt,name=cipher,proto3" json:"cipher,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Deal_EncryptedDeal) Reset()         { *m = Deal_EncryptedDeal{} }
func (m *Deal_EncryptedDeal) String() string { return proto.CompactTextString(m) }
func (*Deal_EncryptedDeal) ProtoMessage()    {}
func (*Deal_EncryptedDeal) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1, 0}
}

func (m *Deal_EncryptedDeal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Deal_EncryptedDeal.Unmarshal(m, b)
}
func (m *Deal_EncryptedDeal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Deal_EncryptedDeal.Marshal(b, m, deterministic)
}
func (m *Deal_EncryptedDeal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Deal_EncryptedDeal.Merge(m, src)
}
func (m *Deal_EncryptedDeal) XXX_Size() int {
	return xxx_messageInfo_Deal_EncryptedDeal.Size(m)
}
func (m *Deal_EncryptedDeal) XXX_DiscardUnknown() {
	xxx_messageInfo_Deal_EncryptedDeal.DiscardUnknown(m)
}

var xxx_messageInfo_Deal_EncryptedDeal proto.InternalMessageInfo

func (m *Deal_EncryptedDeal) GetDhkey() []byte {
	if m != nil {
		return m.Dhkey
	}
	return nil
}

func (m *Deal_EncryptedDeal) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Deal_EncryptedDeal) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *Deal_EncryptedDeal) GetCipher() []byte {
	if m != nil {
		return m.Cipher
	}
	return nil
}

// Matches the attributes defined in kyber pedersen.Response
type Response struct {
	// Index of the Dealer this response is for
	Index                uint32         `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Response             *Response_Data `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Response) GetResponse() *Response_Data {
	if m != nil {
		return m.Response
	}
	return nil
}

type Response_Data struct {
	SessionID []byte `protobuf:"bytes,1,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	// Index of the verifier issuing this Response from the new set of nodes
	Index                uint32   `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Status               bool     `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Signature            []byte   `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_Data) Reset()         { *m = Response_Data{} }
func (m *Response_Data) String() string { return proto.CompactTextString(m) }
func (*Response_Data) ProtoMessage()    {}
func (*Response_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2, 0}
}

func (m *Response_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_Data.Unmarshal(m, b)
}
func (m *Response_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_Data.Marshal(b, m, deterministic)
}
func (m *Response_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_Data.Merge(m, src)
}
func (m *Response_Data) XXX_Size() int {
	return xxx_messageInfo_Response_Data.Size(m)
}
func (m *Response_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Response_Data proto.InternalMessageInfo

func (m *Response_Data) GetSessionID() []byte {
	if m != nil {
		return m.SessionID
	}
	return nil
}

func (m *Response_Data) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Response_Data) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *Response_Data) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

// This message should be sent by all the nodes to the initiator of the DKG when
// the DKG setup is done.
type StartDone struct {
	PubKey               []byte   `protobuf:"bytes,1,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartDone) Reset()         { *m = StartDone{} }
func (m *StartDone) String() string { return proto.CompactTextString(m) }
func (*StartDone) ProtoMessage()    {}
func (*StartDone) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{3}
}

func (m *StartDone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartDone.Unmarshal(m, b)
}
func (m *StartDone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartDone.Marshal(b, m, deterministic)
}
func (m *StartDone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartDone.Merge(m, src)
}
func (m *StartDone) XXX_Size() int {
	return xxx_messageInfo_StartDone.Size(m)
}
func (m *StartDone) XXX_DiscardUnknown() {
	xxx_messageInfo_StartDone.DiscardUnknown(m)
}

var xxx_messageInfo_StartDone proto.InternalMessageInfo

func (m *StartDone) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

type DecryptRequest struct {
	K                    []byte   `protobuf:"bytes,1,opt,name=K,proto3" json:"K,omitempty"`
	C                    []byte   `protobuf:"bytes,2,opt,name=C,proto3" json:"C,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DecryptRequest) Reset()         { *m = DecryptRequest{} }
func (m *DecryptRequest) String() string { return proto.CompactTextString(m) }
func (*DecryptRequest) ProtoMessage()    {}
func (*DecryptRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{4}
}

func (m *DecryptRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecryptRequest.Unmarshal(m, b)
}
func (m *DecryptRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecryptRequest.Marshal(b, m, deterministic)
}
func (m *DecryptRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecryptRequest.Merge(m, src)
}
func (m *DecryptRequest) XXX_Size() int {
	return xxx_messageInfo_DecryptRequest.Size(m)
}
func (m *DecryptRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DecryptRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DecryptRequest proto.InternalMessageInfo

func (m *DecryptRequest) GetK() []byte {
	if m != nil {
		return m.K
	}
	return nil
}

func (m *DecryptRequest) GetC() []byte {
	if m != nil {
		return m.C
	}
	return nil
}

type DecryptReply struct {
	V                    []byte   `protobuf:"bytes,1,opt,name=V,proto3" json:"V,omitempty"`
	I                    int64    `protobuf:"varint,2,opt,name=I,proto3" json:"I,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DecryptReply) Reset()         { *m = DecryptReply{} }
func (m *DecryptReply) String() string { return proto.CompactTextString(m) }
func (*DecryptReply) ProtoMessage()    {}
func (*DecryptReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{5}
}

func (m *DecryptReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecryptReply.Unmarshal(m, b)
}
func (m *DecryptReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecryptReply.Marshal(b, m, deterministic)
}
func (m *DecryptReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecryptReply.Merge(m, src)
}
func (m *DecryptReply) XXX_Size() int {
	return xxx_messageInfo_DecryptReply.Size(m)
}
func (m *DecryptReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DecryptReply.DiscardUnknown(m)
}

var xxx_messageInfo_DecryptReply proto.InternalMessageInfo

func (m *DecryptReply) GetV() []byte {
	if m != nil {
		return m.V
	}
	return nil
}

func (m *DecryptReply) GetI() int64 {
	if m != nil {
		return m.I
	}
	return 0
}

func init() {
	proto.RegisterType((*Start)(nil), "pedersen.Start")
	proto.RegisterType((*Deal)(nil), "pedersen.Deal")
	proto.RegisterType((*Deal_EncryptedDeal)(nil), "pedersen.Deal.EncryptedDeal")
	proto.RegisterType((*Response)(nil), "pedersen.Response")
	proto.RegisterType((*Response_Data)(nil), "pedersen.Response.Data")
	proto.RegisterType((*StartDone)(nil), "pedersen.StartDone")
	proto.RegisterType((*DecryptRequest)(nil), "pedersen.DecryptRequest")
	proto.RegisterType((*DecryptReply)(nil), "pedersen.DecryptReply")
}

func init() {
	proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5)
}

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 368 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xc1, 0x8e, 0x9b, 0x30,
	0x10, 0x95, 0x81, 0x4d, 0xd9, 0x29, 0xd9, 0x03, 0xaa, 0xb6, 0x68, 0xb5, 0x07, 0x44, 0x2f, 0x51,
	0x55, 0x71, 0xe8, 0xfe, 0x41, 0x97, 0x1e, 0xa2, 0xa8, 0x17, 0x57, 0xca, 0xdd, 0x09, 0xa3, 0x04,
	0x35, 0x35, 0x8e, 0xc7, 0x48, 0xe5, 0x0b, 0xfb, 0x3d, 0xfd, 0x83, 0xca, 0xc6, 0x84, 0x10, 0x69,
	0x8f, 0xef, 0xf9, 0xcd, 0xcc, 0x7b, 0xe3, 0x81, 0x87, 0xdf, 0x48, 0x24, 0x0e, 0x48, 0xa5, 0xd2,
	0xad, 0x69, 0xd3, 0x58, 0x61, 0x8d, 0x9a, 0x50, 0x16, 0x3f, 0xe0, 0xee, 0xa7, 0x11, 0xda, 0xa4,
	0x09, 0x30, 0x93, 0xb1, 0x9c, 0xad, 0x96, 0x9c, 0x99, 0xf4, 0x19, 0xee, 0x45, 0x5d, 0x6b, 0x24,
	0x42, 0xca, 0x82, 0x3c, 0x5c, 0x25, 0x7c, 0x22, 0xd2, 0x0c, 0xde, 0xa9, 0x6e, 0xb7, 0xc1, 0x9e,
	0xb2, 0xd0, 0xbd, 0x8d, 0xb0, 0xf8, 0xc7, 0x20, 0xaa, 0x50, 0x9c, 0xd2, 0x0f, 0x70, 0xd7, 0xc8,
	0x1a, 0xff, 0xf8, 0x96, 0x03, 0x48, 0xbf, 0xc1, 0x12, 0xe5, 0x5e, 0xf7, 0xca, 0x60, 0x6d, 0x65,
	0x59, 0x90, 0xb3, 0xd5, 0xfb, 0xaf, 0xcf, 0xe5, 0xe8, 0xa7, 0xb4, 0x6c, 0xf9, 0xfd, 0x5a, 0xc3,
	0xe7, 0x25, 0xd6, 0x1a, 0x35, 0x07, 0x29, 0x4c, 0xa7, 0x31, 0x0b, 0x73, 0x66, 0xad, 0x5d, 0x88,
	0xa7, 0x33, 0x2c, 0x67, 0xd5, 0xd6, 0x48, 0x7d, 0xfc, 0x85, 0xbd, 0x33, 0x92, 0xf0, 0x01, 0xcc,
	0x9b, 0x04, 0x37, 0x4d, 0x6c, 0x8d, 0x6c, 0xe5, 0x7e, 0x6c, 0x3f, 0x80, 0xf4, 0x11, 0x16, 0xfb,
	0x46, 0x1d, 0x51, 0x67, 0x91, 0xa3, 0x3d, 0x2a, 0xfe, 0x32, 0x88, 0x39, 0x92, 0x6a, 0x25, 0xe1,
	0x1b, 0xb9, 0x5f, 0x20, 0xd6, 0x5e, 0xe1, 0x23, 0x7f, 0x9c, 0x22, 0x8f, 0xb5, 0x65, 0x25, 0x8c,
	0xe0, 0x17, 0xe1, 0x93, 0x82, 0xc8, 0x32, 0xce, 0x2b, 0x12, 0x35, 0xad, 0x5c, 0x57, 0x3e, 0xc5,
	0x44, 0x4c, 0x03, 0x83, 0xeb, 0x81, 0x8f, 0xb0, 0x20, 0x23, 0x4c, 0x47, 0x2e, 0x42, 0xcc, 0x3d,
	0x9a, 0xe7, 0x8e, 0x6e, 0x72, 0x17, 0x9f, 0xe0, 0xde, 0x1d, 0x43, 0xd5, 0x4a, 0x17, 0x77, 0xf8,
	0x55, 0x3f, 0xd3, 0xa3, 0xe2, 0x0b, 0x3c, 0x54, 0xe8, 0x36, 0xcc, 0xf1, 0xdc, 0x21, 0xb9, 0xd3,
	0xd9, 0x78, 0x11, 0xdb, 0x58, 0xf4, 0xea, 0x57, 0xca, 0x5e, 0x8b, 0xcf, 0x90, 0x5c, 0xd4, 0xea,
	0xd4, 0xdb, 0xd7, 0xed, 0xa8, 0xdd, 0x5a, 0xb4, 0x76, 0xda, 0x90, 0xb3, 0xf5, 0x6e, 0xe1, 0x8e,
	0xf3, 0xe5, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xeb, 0x8b, 0x1c, 0xa5, 0xae, 0x02, 0x00, 0x00,
}
