// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package threshold

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignatureProto struct {
	Aggregation          *any.Any `protobuf:"bytes,1,opt,name=aggregation,proto3" json:"aggregation,omitempty"`
	Mask                 []byte   `protobuf:"bytes,2,opt,name=mask,proto3" json:"mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignatureProto) Reset()         { *m = SignatureProto{} }
func (m *SignatureProto) String() string { return proto.CompactTextString(m) }
func (*SignatureProto) ProtoMessage()    {}
func (*SignatureProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *SignatureProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignatureProto.Unmarshal(m, b)
}
func (m *SignatureProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignatureProto.Marshal(b, m, deterministic)
}
func (m *SignatureProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignatureProto.Merge(m, src)
}
func (m *SignatureProto) XXX_Size() int {
	return xxx_messageInfo_SignatureProto.Size(m)
}
func (m *SignatureProto) XXX_DiscardUnknown() {
	xxx_messageInfo_SignatureProto.DiscardUnknown(m)
}

var xxx_messageInfo_SignatureProto proto.InternalMessageInfo

func (m *SignatureProto) GetAggregation() *any.Any {
	if m != nil {
		return m.Aggregation
	}
	return nil
}

func (m *SignatureProto) GetMask() []byte {
	if m != nil {
		return m.Mask
	}
	return nil
}

func init() {
	proto.RegisterType((*SignatureProto)(nil), "threshold.SignatureProto")
}

func init() {
	proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5)
}

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 144 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2c, 0xc9, 0x28, 0x4a,
	0x2d, 0xce, 0xc8, 0xcf, 0x49, 0x91, 0x92, 0x4c, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x4b,
	0x24, 0x95, 0xa6, 0xe9, 0x27, 0xe6, 0x55, 0x42, 0x54, 0x29, 0xc5, 0x70, 0xf1, 0x05, 0x67, 0xa6,
	0xe7, 0x25, 0x96, 0x94, 0x16, 0xa5, 0x06, 0x80, 0xf5, 0x99, 0x71, 0x71, 0x27, 0xa6, 0xa7, 0x17,
	0xa5, 0xa6, 0x27, 0x96, 0x64, 0xe6, 0xe7, 0x49, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x1b, 0x89, 0xe8,
	0x41, 0x8c, 0xd0, 0x83, 0x19, 0xa1, 0xe7, 0x98, 0x57, 0x19, 0x84, 0xac, 0x50, 0x48, 0x88, 0x8b,
	0x25, 0x37, 0xb1, 0x38, 0x5b, 0x82, 0x49, 0x81, 0x51, 0x83, 0x27, 0x08, 0xcc, 0x4e, 0x62, 0x03,
	0x2b, 0x37, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x3c, 0xb7, 0xf4, 0x67, 0x9c, 0x00, 0x00, 0x00,
}
