// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package contract

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Instance struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                *any.Any `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	ContractID           string   `protobuf:"bytes,3,opt,name=contractID,proto3" json:"contractID,omitempty"`
	Deleted              bool     `protobuf:"varint,4,opt,name=deleted,proto3" json:"deleted,omitempty"`
	AccessControl        []byte   `protobuf:"bytes,5,opt,name=accessControl,proto3" json:"accessControl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Instance) Reset()         { *m = Instance{} }
func (m *Instance) String() string { return proto.CompactTextString(m) }
func (*Instance) ProtoMessage()    {}
func (*Instance) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *Instance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Instance.Unmarshal(m, b)
}
func (m *Instance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Instance.Marshal(b, m, deterministic)
}
func (m *Instance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Instance.Merge(m, src)
}
func (m *Instance) XXX_Size() int {
	return xxx_messageInfo_Instance.Size(m)
}
func (m *Instance) XXX_DiscardUnknown() {
	xxx_messageInfo_Instance.DiscardUnknown(m)
}

var xxx_messageInfo_Instance proto.InternalMessageInfo

func (m *Instance) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Instance) GetValue() *any.Any {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Instance) GetContractID() string {
	if m != nil {
		return m.ContractID
	}
	return ""
}

func (m *Instance) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func (m *Instance) GetAccessControl() []byte {
	if m != nil {
		return m.AccessControl
	}
	return nil
}

type SpawnActionProto struct {
	ContractID           string   `protobuf:"bytes,1,opt,name=contractID,proto3" json:"contractID,omitempty"`
	Argument             []byte   `protobuf:"bytes,2,opt,name=argument,proto3" json:"argument,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpawnActionProto) Reset()         { *m = SpawnActionProto{} }
func (m *SpawnActionProto) String() string { return proto.CompactTextString(m) }
func (*SpawnActionProto) ProtoMessage()    {}
func (*SpawnActionProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *SpawnActionProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpawnActionProto.Unmarshal(m, b)
}
func (m *SpawnActionProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpawnActionProto.Marshal(b, m, deterministic)
}
func (m *SpawnActionProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpawnActionProto.Merge(m, src)
}
func (m *SpawnActionProto) XXX_Size() int {
	return xxx_messageInfo_SpawnActionProto.Size(m)
}
func (m *SpawnActionProto) XXX_DiscardUnknown() {
	xxx_messageInfo_SpawnActionProto.DiscardUnknown(m)
}

var xxx_messageInfo_SpawnActionProto proto.InternalMessageInfo

func (m *SpawnActionProto) GetContractID() string {
	if m != nil {
		return m.ContractID
	}
	return ""
}

func (m *SpawnActionProto) GetArgument() []byte {
	if m != nil {
		return m.Argument
	}
	return nil
}

type InvokeActionProto struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Argument             []byte   `protobuf:"bytes,2,opt,name=argument,proto3" json:"argument,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvokeActionProto) Reset()         { *m = InvokeActionProto{} }
func (m *InvokeActionProto) String() string { return proto.CompactTextString(m) }
func (*InvokeActionProto) ProtoMessage()    {}
func (*InvokeActionProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2}
}

func (m *InvokeActionProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvokeActionProto.Unmarshal(m, b)
}
func (m *InvokeActionProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvokeActionProto.Marshal(b, m, deterministic)
}
func (m *InvokeActionProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvokeActionProto.Merge(m, src)
}
func (m *InvokeActionProto) XXX_Size() int {
	return xxx_messageInfo_InvokeActionProto.Size(m)
}
func (m *InvokeActionProto) XXX_DiscardUnknown() {
	xxx_messageInfo_InvokeActionProto.DiscardUnknown(m)
}

var xxx_messageInfo_InvokeActionProto proto.InternalMessageInfo

func (m *InvokeActionProto) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *InvokeActionProto) GetArgument() []byte {
	if m != nil {
		return m.Argument
	}
	return nil
}

type DeleteActionProto struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteActionProto) Reset()         { *m = DeleteActionProto{} }
func (m *DeleteActionProto) String() string { return proto.CompactTextString(m) }
func (*DeleteActionProto) ProtoMessage()    {}
func (*DeleteActionProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{3}
}

func (m *DeleteActionProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteActionProto.Unmarshal(m, b)
}
func (m *DeleteActionProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteActionProto.Marshal(b, m, deterministic)
}
func (m *DeleteActionProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteActionProto.Merge(m, src)
}
func (m *DeleteActionProto) XXX_Size() int {
	return xxx_messageInfo_DeleteActionProto.Size(m)
}
func (m *DeleteActionProto) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteActionProto.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteActionProto proto.InternalMessageInfo

func (m *DeleteActionProto) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func init() {
	proto.RegisterType((*Instance)(nil), "contract.Instance")
	proto.RegisterType((*SpawnActionProto)(nil), "contract.SpawnActionProto")
	proto.RegisterType((*InvokeActionProto)(nil), "contract.InvokeActionProto")
	proto.RegisterType((*DeleteActionProto)(nil), "contract.DeleteActionProto")
}

func init() {
	proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5)
}

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x51, 0x4b, 0xc3, 0x30,
	0x14, 0x85, 0x89, 0x73, 0x5a, 0xaf, 0x53, 0xb6, 0xe0, 0x43, 0xdc, 0x83, 0x94, 0xa2, 0x50, 0x7c,
	0xe8, 0x40, 0x7f, 0x41, 0x71, 0x2f, 0x7d, 0x11, 0x89, 0xbf, 0x20, 0xcb, 0xae, 0x45, 0xd6, 0xdd,
	0x3b, 0x9a, 0x74, 0xd2, 0x7f, 0xe4, 0xcf, 0x94, 0xa5, 0x54, 0x36, 0x06, 0x7b, 0xcb, 0x3d, 0x1c,
	0xbe, 0x93, 0x73, 0xe0, 0x76, 0x8d, 0xce, 0x99, 0x12, 0x5d, 0xb6, 0xa9, 0xd9, 0xb3, 0x8c, 0x2c,
	0x93, 0xaf, 0x8d, 0xf5, 0xd3, 0xfb, 0x92, 0xb9, 0xac, 0x70, 0x16, 0xf4, 0x45, 0xf3, 0x35, 0x33,
	0xd4, 0x76, 0xa6, 0xe4, 0x57, 0x40, 0x54, 0x90, 0xf3, 0x86, 0x2c, 0xca, 0x31, 0x0c, 0x56, 0xd8,
	0x2a, 0x11, 0x8b, 0x74, 0xa4, 0x77, 0x4f, 0xf9, 0x0c, 0xc3, 0xad, 0xa9, 0x1a, 0x54, 0x67, 0xb1,
	0x48, 0xaf, 0x5f, 0xee, 0xb2, 0x8e, 0x94, 0xf5, 0xa4, 0x2c, 0xa7, 0x56, 0x77, 0x16, 0xf9, 0x00,
	0xd0, 0x27, 0x16, 0x73, 0x35, 0x88, 0x45, 0x7a, 0xa5, 0xf7, 0x14, 0xa9, 0xe0, 0x72, 0x89, 0x15,
	0x7a, 0x5c, 0xaa, 0xf3, 0x58, 0xa4, 0x91, 0xee, 0x4f, 0xf9, 0x08, 0x37, 0xc6, 0x5a, 0x74, 0xee,
	0x6d, 0xe7, 0xe6, 0x4a, 0x0d, 0xc3, 0x0f, 0x0e, 0xc5, 0xe4, 0x1d, 0xc6, 0x9f, 0x1b, 0xf3, 0x43,
	0xb9, 0xf5, 0xdf, 0x4c, 0x1f, 0xa1, 0xe3, 0x61, 0xa6, 0x38, 0xca, 0x9c, 0x42, 0x64, 0xea, 0xb2,
	0x59, 0x23, 0xf9, 0x50, 0x61, 0xa4, 0xff, 0xef, 0x24, 0x87, 0x49, 0x41, 0x5b, 0x5e, 0xe1, 0x3e,
	0xf0, 0x78, 0x82, 0x53, 0x88, 0x27, 0x98, 0xcc, 0x43, 0x87, 0x93, 0x88, 0xc5, 0x45, 0x98, 0xeb,
	0xf5, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xe2, 0x94, 0x99, 0xe1, 0xa2, 0x01, 0x00, 0x00,
}
