// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package cosipbft

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ForwardLinkProto struct {
	From                 []byte   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   []byte   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Prepare              *any.Any `protobuf:"bytes,3,opt,name=prepare,proto3" json:"prepare,omitempty"`
	Commit               *any.Any `protobuf:"bytes,4,opt,name=commit,proto3" json:"commit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForwardLinkProto) Reset()         { *m = ForwardLinkProto{} }
func (m *ForwardLinkProto) String() string { return proto.CompactTextString(m) }
func (*ForwardLinkProto) ProtoMessage()    {}
func (*ForwardLinkProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *ForwardLinkProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForwardLinkProto.Unmarshal(m, b)
}
func (m *ForwardLinkProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForwardLinkProto.Marshal(b, m, deterministic)
}
func (m *ForwardLinkProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForwardLinkProto.Merge(m, src)
}
func (m *ForwardLinkProto) XXX_Size() int {
	return xxx_messageInfo_ForwardLinkProto.Size(m)
}
func (m *ForwardLinkProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ForwardLinkProto.DiscardUnknown(m)
}

var xxx_messageInfo_ForwardLinkProto proto.InternalMessageInfo

func (m *ForwardLinkProto) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *ForwardLinkProto) GetTo() []byte {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *ForwardLinkProto) GetPrepare() *any.Any {
	if m != nil {
		return m.Prepare
	}
	return nil
}

func (m *ForwardLinkProto) GetCommit() *any.Any {
	if m != nil {
		return m.Commit
	}
	return nil
}

type PrepareSignatureRequest struct {
	From                 []byte   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Proposal             *any.Any `protobuf:"bytes,2,opt,name=proposal,proto3" json:"proposal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrepareSignatureRequest) Reset()         { *m = PrepareSignatureRequest{} }
func (m *PrepareSignatureRequest) String() string { return proto.CompactTextString(m) }
func (*PrepareSignatureRequest) ProtoMessage()    {}
func (*PrepareSignatureRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *PrepareSignatureRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrepareSignatureRequest.Unmarshal(m, b)
}
func (m *PrepareSignatureRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrepareSignatureRequest.Marshal(b, m, deterministic)
}
func (m *PrepareSignatureRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrepareSignatureRequest.Merge(m, src)
}
func (m *PrepareSignatureRequest) XXX_Size() int {
	return xxx_messageInfo_PrepareSignatureRequest.Size(m)
}
func (m *PrepareSignatureRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrepareSignatureRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrepareSignatureRequest proto.InternalMessageInfo

func (m *PrepareSignatureRequest) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *PrepareSignatureRequest) GetProposal() *any.Any {
	if m != nil {
		return m.Proposal
	}
	return nil
}

func init() {
	proto.RegisterType((*ForwardLinkProto)(nil), "cosipbft.ForwardLinkProto")
	proto.RegisterType((*PrepareSignatureRequest)(nil), "cosipbft.PrepareSignatureRequest")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5) }

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x8e, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0xc9, 0x5a, 0x6a, 0x19, 0xa5, 0x48, 0x10, 0x8c, 0x9e, 0x4a, 0x4f, 0x3d, 0x48, 0x2a,
	0xfa, 0x04, 0x5e, 0x3c, 0x79, 0x28, 0xeb, 0x03, 0x48, 0x76, 0x9d, 0x0d, 0xc1, 0x4d, 0x26, 0x4e,
	0xb2, 0xc8, 0xbe, 0x87, 0x0f, 0x2c, 0x64, 0x5d, 0x4f, 0xda, 0xdb, 0xf0, 0xf1, 0xfd, 0xf3, 0xff,
	0xb0, 0xf6, 0x98, 0x92, 0xb1, 0x98, 0x74, 0x64, 0xca, 0x24, 0x57, 0x2d, 0x25, 0x17, 0x9b, 0x2e,
	0xdf, 0x5c, 0x5b, 0x22, 0xdb, 0xe3, 0xbe, 0xf0, 0x66, 0xe8, 0xf6, 0x26, 0x8c, 0x93, 0xb4, 0xfd,
	0x12, 0x70, 0xf1, 0x44, 0xfc, 0x69, 0xf8, 0xed, 0xd9, 0x85, 0xf7, 0x43, 0x49, 0x4a, 0x58, 0x74,
	0x4c, 0x5e, 0x89, 0x8d, 0xd8, 0x9d, 0xd7, 0xe5, 0x96, 0x6b, 0xa8, 0x32, 0xa9, 0xaa, 0x90, 0x2a,
	0x93, 0xd4, 0x70, 0x1a, 0x19, 0xa3, 0x61, 0x54, 0x27, 0x1b, 0xb1, 0x3b, 0xbb, 0xbf, 0xd4, 0x53,
	0x8b, 0x9e, 0x5b, 0xf4, 0x63, 0x18, 0xeb, 0x59, 0x92, 0xb7, 0xb0, 0x6c, 0xc9, 0x7b, 0x97, 0xd5,
	0xe2, 0x88, 0xfe, 0xe3, 0x6c, 0x5f, 0xe1, 0xea, 0x30, 0x05, 0x5f, 0x9c, 0x0d, 0x26, 0x0f, 0x8c,
	0x35, 0x7e, 0x0c, 0x98, 0xf2, 0x9f, 0xe3, 0xee, 0x60, 0x15, 0x99, 0x22, 0x25, 0xd3, 0x97, 0x89,
	0xff, 0xbd, 0xff, 0xb5, 0x9a, 0x65, 0xe1, 0x0f, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x74, 0x8e,
	0x9e, 0x9f, 0x35, 0x01, 0x00, 0x00,
}
