// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package skipchain

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// BlockProto is the message that contains the minimal data to instantiate a
// block. It is not sufficient to prove the block integrity as the chain from
// the genesis block is missing.
type BlockProto struct {
	Index                uint64   `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	GenesisID            []byte   `protobuf:"bytes,2,opt,name=genesisID,proto3" json:"genesisID,omitempty"`
	Backlink             []byte   `protobuf:"bytes,3,opt,name=backlink,proto3" json:"backlink,omitempty"`
	Payload              *any.Any `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockProto) Reset()         { *m = BlockProto{} }
func (m *BlockProto) String() string { return proto.CompactTextString(m) }
func (*BlockProto) ProtoMessage()    {}
func (*BlockProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *BlockProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockProto.Unmarshal(m, b)
}
func (m *BlockProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockProto.Marshal(b, m, deterministic)
}
func (m *BlockProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockProto.Merge(m, src)
}
func (m *BlockProto) XXX_Size() int {
	return xxx_messageInfo_BlockProto.Size(m)
}
func (m *BlockProto) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockProto.DiscardUnknown(m)
}

var xxx_messageInfo_BlockProto proto.InternalMessageInfo

func (m *BlockProto) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *BlockProto) GetGenesisID() []byte {
	if m != nil {
		return m.GenesisID
	}
	return nil
}

func (m *BlockProto) GetBacklink() []byte {
	if m != nil {
		return m.Backlink
	}
	return nil
}

func (m *BlockProto) GetPayload() *any.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

// VerifiableBlockProto is the message that contains a verifiable block. It
// contains everything necessary to prove a block is valid as long as the
// receiver has the genesis block.
type VerifiableBlockProto struct {
	Block                *BlockProto `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	Chain                *any.Any    `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *VerifiableBlockProto) Reset()         { *m = VerifiableBlockProto{} }
func (m *VerifiableBlockProto) String() string { return proto.CompactTextString(m) }
func (*VerifiableBlockProto) ProtoMessage()    {}
func (*VerifiableBlockProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *VerifiableBlockProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifiableBlockProto.Unmarshal(m, b)
}
func (m *VerifiableBlockProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifiableBlockProto.Marshal(b, m, deterministic)
}
func (m *VerifiableBlockProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifiableBlockProto.Merge(m, src)
}
func (m *VerifiableBlockProto) XXX_Size() int {
	return xxx_messageInfo_VerifiableBlockProto.Size(m)
}
func (m *VerifiableBlockProto) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifiableBlockProto.DiscardUnknown(m)
}

var xxx_messageInfo_VerifiableBlockProto proto.InternalMessageInfo

func (m *VerifiableBlockProto) GetBlock() *BlockProto {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *VerifiableBlockProto) GetChain() *any.Any {
	if m != nil {
		return m.Chain
	}
	return nil
}

// PropagateGenesis is the message containing a genesis to be transmitted to the
// participants.
type PropagateGenesis struct {
	Genesis              *BlockProto `protobuf:"bytes,1,opt,name=genesis,proto3" json:"genesis,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PropagateGenesis) Reset()         { *m = PropagateGenesis{} }
func (m *PropagateGenesis) String() string { return proto.CompactTextString(m) }
func (*PropagateGenesis) ProtoMessage()    {}
func (*PropagateGenesis) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2}
}

func (m *PropagateGenesis) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PropagateGenesis.Unmarshal(m, b)
}
func (m *PropagateGenesis) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PropagateGenesis.Marshal(b, m, deterministic)
}
func (m *PropagateGenesis) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PropagateGenesis.Merge(m, src)
}
func (m *PropagateGenesis) XXX_Size() int {
	return xxx_messageInfo_PropagateGenesis.Size(m)
}
func (m *PropagateGenesis) XXX_DiscardUnknown() {
	xxx_messageInfo_PropagateGenesis.DiscardUnknown(m)
}

var xxx_messageInfo_PropagateGenesis proto.InternalMessageInfo

func (m *PropagateGenesis) GetGenesis() *BlockProto {
	if m != nil {
		return m.Genesis
	}
	return nil
}

type BlockRequest struct {
	From                 uint64   `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   uint64   `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockRequest) Reset()         { *m = BlockRequest{} }
func (m *BlockRequest) String() string { return proto.CompactTextString(m) }
func (*BlockRequest) ProtoMessage()    {}
func (*BlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{3}
}

func (m *BlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockRequest.Unmarshal(m, b)
}
func (m *BlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockRequest.Marshal(b, m, deterministic)
}
func (m *BlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRequest.Merge(m, src)
}
func (m *BlockRequest) XXX_Size() int {
	return xxx_messageInfo_BlockRequest.Size(m)
}
func (m *BlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRequest proto.InternalMessageInfo

func (m *BlockRequest) GetFrom() uint64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *BlockRequest) GetTo() uint64 {
	if m != nil {
		return m.To
	}
	return 0
}

type BlockResponse struct {
	Block                *BlockProto `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	Chain                *any.Any    `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *BlockResponse) Reset()         { *m = BlockResponse{} }
func (m *BlockResponse) String() string { return proto.CompactTextString(m) }
func (*BlockResponse) ProtoMessage()    {}
func (*BlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{4}
}

func (m *BlockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockResponse.Unmarshal(m, b)
}
func (m *BlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockResponse.Marshal(b, m, deterministic)
}
func (m *BlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockResponse.Merge(m, src)
}
func (m *BlockResponse) XXX_Size() int {
	return xxx_messageInfo_BlockResponse.Size(m)
}
func (m *BlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlockResponse proto.InternalMessageInfo

func (m *BlockResponse) GetBlock() *BlockProto {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *BlockResponse) GetChain() *any.Any {
	if m != nil {
		return m.Chain
	}
	return nil
}

func init() {
	proto.RegisterType((*BlockProto)(nil), "skipchain.BlockProto")
	proto.RegisterType((*VerifiableBlockProto)(nil), "skipchain.VerifiableBlockProto")
	proto.RegisterType((*PropagateGenesis)(nil), "skipchain.PropagateGenesis")
	proto.RegisterType((*BlockRequest)(nil), "skipchain.BlockRequest")
	proto.RegisterType((*BlockResponse)(nil), "skipchain.BlockResponse")
}

func init() {
	proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5)
}

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x90, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0x87, 0x49, 0xdf, 0xf4, 0xad, 0x9d, 0xd6, 0x22, 0x4b, 0x85, 0x58, 0x3c, 0x94, 0x9c, 0x82,
	0xc2, 0x06, 0xe2, 0x27, 0xf0, 0x0f, 0x88, 0xb7, 0xb2, 0x07, 0xef, 0x9b, 0x74, 0x92, 0x2e, 0x49,
	0x77, 0x62, 0x36, 0x05, 0xf3, 0x1d, 0xfc, 0xd0, 0xe2, 0x6e, 0xd2, 0x7a, 0xd1, 0x9b, 0xb7, 0x9d,
	0x99, 0x67, 0x98, 0xe7, 0xb7, 0xb0, 0xd8, 0xa3, 0x31, 0xb2, 0x40, 0xc3, 0xeb, 0x86, 0x5a, 0x62,
	0x53, 0x53, 0xaa, 0x3a, 0xdb, 0x49, 0xa5, 0x57, 0x57, 0x05, 0x51, 0x51, 0x61, 0x6c, 0x07, 0xe9,
	0x21, 0x8f, 0xa5, 0xee, 0x1c, 0x15, 0x7e, 0x78, 0x00, 0x0f, 0x15, 0x65, 0xe5, 0xc6, 0x2e, 0x2d,
	0x61, 0xac, 0xf4, 0x16, 0xdf, 0x03, 0x6f, 0xed, 0x45, 0xbe, 0x70, 0x05, 0xbb, 0x86, 0x69, 0x81,
	0x1a, 0x8d, 0x32, 0x2f, 0x4f, 0xc1, 0x68, 0xed, 0x45, 0x73, 0x71, 0x6a, 0xb0, 0x15, 0x9c, 0xa5,
	0x32, 0x2b, 0x2b, 0xa5, 0xcb, 0xe0, 0x9f, 0x1d, 0x1e, 0x6b, 0xc6, 0x61, 0x52, 0xcb, 0xae, 0x22,
	0xb9, 0x0d, 0xfc, 0xb5, 0x17, 0xcd, 0x92, 0x25, 0x77, 0x2e, 0x7c, 0x70, 0xe1, 0xf7, 0xba, 0x13,
	0x03, 0x14, 0x12, 0x2c, 0x5f, 0xb1, 0x51, 0xb9, 0x92, 0x69, 0x85, 0xdf, 0xbc, 0x6e, 0x61, 0x9c,
	0x7e, 0x55, 0xd6, 0x6b, 0x96, 0x5c, 0xf2, 0x63, 0x38, 0x7e, 0xa2, 0x84, 0x63, 0xd8, 0x0d, 0x8c,
	0xed, 0xc8, 0xaa, 0xfe, 0x74, 0xd2, 0x21, 0xe1, 0x23, 0x5c, 0x6c, 0x1a, 0xaa, 0x65, 0x21, 0x5b,
	0x7c, 0x76, 0x91, 0x58, 0x0c, 0x93, 0x3e, 0xdd, 0xef, 0xe7, 0x06, 0x2a, 0x4c, 0x60, 0x6e, 0xdb,
	0x02, 0xdf, 0x0e, 0x68, 0x5a, 0xc6, 0xc0, 0xcf, 0x1b, 0xda, 0xf7, 0x9f, 0x68, 0xdf, 0x6c, 0x01,
	0xa3, 0x96, 0xac, 0x91, 0x2f, 0x46, 0x2d, 0x85, 0x3b, 0x38, 0xef, 0x77, 0x4c, 0x4d, 0xda, 0xe0,
	0x9f, 0x45, 0x4c, 0xff, 0xdb, 0xe6, 0xdd, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc8, 0xf6, 0xc0,
	0xb7, 0x21, 0x02, 0x00, 0x00,
}
