// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package skipchain

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConodeProto struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	PublicKey            *any.Any `protobuf:"bytes,2,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConodeProto) Reset()         { *m = ConodeProto{} }
func (m *ConodeProto) String() string { return proto.CompactTextString(m) }
func (*ConodeProto) ProtoMessage()    {}
func (*ConodeProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *ConodeProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConodeProto.Unmarshal(m, b)
}
func (m *ConodeProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConodeProto.Marshal(b, m, deterministic)
}
func (m *ConodeProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConodeProto.Merge(m, src)
}
func (m *ConodeProto) XXX_Size() int {
	return xxx_messageInfo_ConodeProto.Size(m)
}
func (m *ConodeProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ConodeProto.DiscardUnknown(m)
}

var xxx_messageInfo_ConodeProto proto.InternalMessageInfo

func (m *ConodeProto) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *ConodeProto) GetPublicKey() *any.Any {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type BlockProto struct {
	Index                uint64         `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Height               uint32         `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	BaseHeight           uint32         `protobuf:"varint,3,opt,name=baseHeight,proto3" json:"baseHeight,omitempty"`
	MaximumHeight        uint32         `protobuf:"varint,4,opt,name=maximumHeight,proto3" json:"maximumHeight,omitempty"`
	GenesisID            []byte         `protobuf:"bytes,5,opt,name=genesisID,proto3" json:"genesisID,omitempty"`
	DataHash             []byte         `protobuf:"bytes,6,opt,name=dataHash,proto3" json:"dataHash,omitempty"`
	Payload              *any.Any       `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	Conodes              []*ConodeProto `protobuf:"bytes,8,rep,name=conodes,proto3" json:"conodes,omitempty"`
	Backlinks            [][]byte       `protobuf:"bytes,9,rep,name=backlinks,proto3" json:"backlinks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BlockProto) Reset()         { *m = BlockProto{} }
func (m *BlockProto) String() string { return proto.CompactTextString(m) }
func (*BlockProto) ProtoMessage()    {}
func (*BlockProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *BlockProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockProto.Unmarshal(m, b)
}
func (m *BlockProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockProto.Marshal(b, m, deterministic)
}
func (m *BlockProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockProto.Merge(m, src)
}
func (m *BlockProto) XXX_Size() int {
	return xxx_messageInfo_BlockProto.Size(m)
}
func (m *BlockProto) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockProto.DiscardUnknown(m)
}

var xxx_messageInfo_BlockProto proto.InternalMessageInfo

func (m *BlockProto) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *BlockProto) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *BlockProto) GetBaseHeight() uint32 {
	if m != nil {
		return m.BaseHeight
	}
	return 0
}

func (m *BlockProto) GetMaximumHeight() uint32 {
	if m != nil {
		return m.MaximumHeight
	}
	return 0
}

func (m *BlockProto) GetGenesisID() []byte {
	if m != nil {
		return m.GenesisID
	}
	return nil
}

func (m *BlockProto) GetDataHash() []byte {
	if m != nil {
		return m.DataHash
	}
	return nil
}

func (m *BlockProto) GetPayload() *any.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *BlockProto) GetConodes() []*ConodeProto {
	if m != nil {
		return m.Conodes
	}
	return nil
}

func (m *BlockProto) GetBacklinks() [][]byte {
	if m != nil {
		return m.Backlinks
	}
	return nil
}

type VerifiableBlockProto struct {
	Block                *BlockProto `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	Chain                *any.Any    `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *VerifiableBlockProto) Reset()         { *m = VerifiableBlockProto{} }
func (m *VerifiableBlockProto) String() string { return proto.CompactTextString(m) }
func (*VerifiableBlockProto) ProtoMessage()    {}
func (*VerifiableBlockProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2}
}

func (m *VerifiableBlockProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifiableBlockProto.Unmarshal(m, b)
}
func (m *VerifiableBlockProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifiableBlockProto.Marshal(b, m, deterministic)
}
func (m *VerifiableBlockProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifiableBlockProto.Merge(m, src)
}
func (m *VerifiableBlockProto) XXX_Size() int {
	return xxx_messageInfo_VerifiableBlockProto.Size(m)
}
func (m *VerifiableBlockProto) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifiableBlockProto.DiscardUnknown(m)
}

var xxx_messageInfo_VerifiableBlockProto proto.InternalMessageInfo

func (m *VerifiableBlockProto) GetBlock() *BlockProto {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *VerifiableBlockProto) GetChain() *any.Any {
	if m != nil {
		return m.Chain
	}
	return nil
}

type PropagateGenesis struct {
	Genesis              *BlockProto `protobuf:"bytes,1,opt,name=genesis,proto3" json:"genesis,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PropagateGenesis) Reset()         { *m = PropagateGenesis{} }
func (m *PropagateGenesis) String() string { return proto.CompactTextString(m) }
func (*PropagateGenesis) ProtoMessage()    {}
func (*PropagateGenesis) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{3}
}

func (m *PropagateGenesis) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PropagateGenesis.Unmarshal(m, b)
}
func (m *PropagateGenesis) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PropagateGenesis.Marshal(b, m, deterministic)
}
func (m *PropagateGenesis) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PropagateGenesis.Merge(m, src)
}
func (m *PropagateGenesis) XXX_Size() int {
	return xxx_messageInfo_PropagateGenesis.Size(m)
}
func (m *PropagateGenesis) XXX_DiscardUnknown() {
	xxx_messageInfo_PropagateGenesis.DiscardUnknown(m)
}

var xxx_messageInfo_PropagateGenesis proto.InternalMessageInfo

func (m *PropagateGenesis) GetGenesis() *BlockProto {
	if m != nil {
		return m.Genesis
	}
	return nil
}

func init() {
	proto.RegisterType((*ConodeProto)(nil), "skipchain.ConodeProto")
	proto.RegisterType((*BlockProto)(nil), "skipchain.BlockProto")
	proto.RegisterType((*VerifiableBlockProto)(nil), "skipchain.VerifiableBlockProto")
	proto.RegisterType((*PropagateGenesis)(nil), "skipchain.PropagateGenesis")
}

func init() {
	proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5)
}

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 363 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xcd, 0x6a, 0xe3, 0x30,
	0x14, 0x85, 0xc9, 0x8f, 0xe3, 0xf8, 0x7a, 0x32, 0x0c, 0x22, 0x13, 0x34, 0x61, 0x18, 0x8c, 0x99,
	0x45, 0x98, 0x01, 0xa7, 0xb8, 0x4f, 0xd0, 0xa6, 0xd0, 0x94, 0x6e, 0x82, 0x17, 0xdd, 0x74, 0x75,
	0x6d, 0x2b, 0xb6, 0xf0, 0x8f, 0x8c, 0xe5, 0x40, 0xfc, 0x6a, 0x7d, 0xba, 0x12, 0x29, 0x4e, 0xdc,
	0x4d, 0x96, 0xe7, 0x9e, 0x4f, 0x47, 0xd2, 0xb9, 0xf0, 0xbd, 0x60, 0x52, 0x62, 0xc2, 0xa4, 0x57,
	0xd5, 0xa2, 0x11, 0xc4, 0x92, 0x19, 0xaf, 0xa2, 0x14, 0x79, 0xb9, 0xfc, 0x95, 0x08, 0x91, 0xe4,
	0x6c, 0xad, 0x8c, 0xf0, 0xb0, 0x5f, 0x63, 0xd9, 0x6a, 0xca, 0x7d, 0x07, 0x7b, 0x23, 0x4a, 0x11,
	0xb3, 0x9d, 0x3a, 0x44, 0xc1, 0xc4, 0x38, 0xae, 0x99, 0x94, 0x74, 0xe0, 0x0c, 0x56, 0xdf, 0x82,
	0x4e, 0x12, 0x1f, 0xac, 0xea, 0x10, 0xe6, 0x3c, 0x7a, 0x65, 0x2d, 0x1d, 0x3a, 0x83, 0x95, 0xed,
	0xcf, 0x3d, 0x9d, 0xeb, 0x75, 0xb9, 0xde, 0x43, 0xd9, 0x06, 0x57, 0xcc, 0xfd, 0x18, 0x02, 0x3c,
	0xe6, 0x22, 0xca, 0x74, 0xf8, 0x1c, 0x0c, 0x5e, 0xc6, 0xec, 0xa8, 0xa2, 0xc7, 0x81, 0x16, 0x64,
	0x01, 0x93, 0x94, 0xf1, 0x24, 0x6d, 0x54, 0xea, 0x2c, 0x38, 0x2b, 0xf2, 0x07, 0x20, 0x44, 0xc9,
	0xb6, 0xda, 0x1b, 0x29, 0xaf, 0x37, 0x21, 0x7f, 0x61, 0x56, 0xe0, 0x91, 0x17, 0x87, 0xe2, 0x8c,
	0x8c, 0x15, 0xf2, 0x75, 0x48, 0x7e, 0x83, 0x95, 0xb0, 0x92, 0x49, 0x2e, 0x5f, 0x9e, 0xa8, 0xa1,
	0xbe, 0x74, 0x1d, 0x90, 0x25, 0x4c, 0x63, 0x6c, 0x70, 0x8b, 0x32, 0xa5, 0x13, 0x65, 0x5e, 0x34,
	0xf1, 0xc0, 0xac, 0xb0, 0xcd, 0x05, 0xc6, 0xd4, 0xbc, 0xf1, 0xdd, 0x0e, 0x22, 0x77, 0x60, 0x46,
	0xaa, 0x49, 0x49, 0xa7, 0xce, 0x68, 0x65, 0xfb, 0x0b, 0xef, 0xb2, 0x01, 0xaf, 0xd7, 0x71, 0xd0,
	0x61, 0xa7, 0xb7, 0x85, 0x18, 0x65, 0x39, 0x2f, 0x33, 0x49, 0x2d, 0x67, 0x74, 0x7a, 0xdb, 0x65,
	0xe0, 0x0a, 0x98, 0xbf, 0xb1, 0x9a, 0xef, 0x39, 0x86, 0x39, 0xeb, 0xb5, 0xf8, 0x1f, 0x8c, 0xf0,
	0xa4, 0x54, 0x8b, 0xb6, 0xff, 0xb3, 0x77, 0xcb, 0x95, 0x0a, 0x34, 0x43, 0xfe, 0x81, 0xa1, 0xac,
	0x9b, 0x1b, 0xd3, 0x88, 0xbb, 0x81, 0x1f, 0xbb, 0x5a, 0x54, 0x98, 0x60, 0xc3, 0x9e, 0x75, 0x45,
	0x64, 0x0d, 0xe6, 0xb9, 0xad, 0xdb, 0xd7, 0x75, 0x54, 0x38, 0x51, 0xc9, 0xf7, 0x9f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x2c, 0xea, 0xe2, 0x42, 0x8e, 0x02, 0x00, 0x00,
}
