// Code generated by protoc-gen-go. DO NOT EDIT.
// source: overlay.proto

package ptypes

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Certificate is a wrapper around a x509 raw certificate and its address.
type Certificate struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Certificate) Reset()         { *m = Certificate{} }
func (m *Certificate) String() string { return proto.CompactTextString(m) }
func (*Certificate) ProtoMessage()    {}
func (*Certificate) Descriptor() ([]byte, []int) {
	return fileDescriptor_61fc82527fbe24ad, []int{0}
}

func (m *Certificate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Certificate.Unmarshal(m, b)
}
func (m *Certificate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Certificate.Marshal(b, m, deterministic)
}
func (m *Certificate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Certificate.Merge(m, src)
}
func (m *Certificate) XXX_Size() int {
	return xxx_messageInfo_Certificate.Size(m)
}
func (m *Certificate) XXX_DiscardUnknown() {
	xxx_messageInfo_Certificate.DiscardUnknown(m)
}

var xxx_messageInfo_Certificate proto.InternalMessageInfo

func (m *Certificate) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Certificate) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type CertificateAck struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CertificateAck) Reset()         { *m = CertificateAck{} }
func (m *CertificateAck) String() string { return proto.CompactTextString(m) }
func (*CertificateAck) ProtoMessage()    {}
func (*CertificateAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_61fc82527fbe24ad, []int{1}
}

func (m *CertificateAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CertificateAck.Unmarshal(m, b)
}
func (m *CertificateAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CertificateAck.Marshal(b, m, deterministic)
}
func (m *CertificateAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CertificateAck.Merge(m, src)
}
func (m *CertificateAck) XXX_Size() int {
	return xxx_messageInfo_CertificateAck.Size(m)
}
func (m *CertificateAck) XXX_DiscardUnknown() {
	xxx_messageInfo_CertificateAck.DiscardUnknown(m)
}

var xxx_messageInfo_CertificateAck proto.InternalMessageInfo

// JoinRequest sends a request to join a network to a distant node. It must
// contain a valid token and its own certificate.
type JoinRequest struct {
	Token                string       `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Certificate          *Certificate `protobuf:"bytes,2,opt,name=certificate,proto3" json:"certificate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *JoinRequest) Reset()         { *m = JoinRequest{} }
func (m *JoinRequest) String() string { return proto.CompactTextString(m) }
func (*JoinRequest) ProtoMessage()    {}
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61fc82527fbe24ad, []int{2}
}

func (m *JoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRequest.Unmarshal(m, b)
}
func (m *JoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRequest.Marshal(b, m, deterministic)
}
func (m *JoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRequest.Merge(m, src)
}
func (m *JoinRequest) XXX_Size() int {
	return xxx_messageInfo_JoinRequest.Size(m)
}
func (m *JoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRequest proto.InternalMessageInfo

func (m *JoinRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *JoinRequest) GetCertificate() *Certificate {
	if m != nil {
		return m.Certificate
	}
	return nil
}

// JoinResponse is a response of a join request that contains the list of
// certificates known by the distant node.
type JoinResponse struct {
	Peers                []*Certificate `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *JoinResponse) Reset()         { *m = JoinResponse{} }
func (m *JoinResponse) String() string { return proto.CompactTextString(m) }
func (*JoinResponse) ProtoMessage()    {}
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61fc82527fbe24ad, []int{3}
}

func (m *JoinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinResponse.Unmarshal(m, b)
}
func (m *JoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinResponse.Marshal(b, m, deterministic)
}
func (m *JoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinResponse.Merge(m, src)
}
func (m *JoinResponse) XXX_Size() int {
	return xxx_messageInfo_JoinResponse.Size(m)
}
func (m *JoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinResponse proto.InternalMessageInfo

func (m *JoinResponse) GetPeers() []*Certificate {
	if m != nil {
		return m.Peers
	}
	return nil
}

// Message is a network message that contains the address of the sender and the
// payload.
type Message struct {
	From                 []byte   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Payload              []byte   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_61fc82527fbe24ad, []int{4}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Message) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// Packet is a wrapper around a packet.
type Packet struct {
	Serialized           []byte   `protobuf:"bytes,1,opt,name=serialized,proto3" json:"serialized,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Packet) Reset()         { *m = Packet{} }
func (m *Packet) String() string { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()    {}
func (*Packet) Descriptor() ([]byte, []int) {
	return fileDescriptor_61fc82527fbe24ad, []int{5}
}

func (m *Packet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet.Unmarshal(m, b)
}
func (m *Packet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet.Marshal(b, m, deterministic)
}
func (m *Packet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet.Merge(m, src)
}
func (m *Packet) XXX_Size() int {
	return xxx_messageInfo_Packet.Size(m)
}
func (m *Packet) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet.DiscardUnknown(m)
}

var xxx_messageInfo_Packet proto.InternalMessageInfo

func (m *Packet) GetSerialized() []byte {
	if m != nil {
		return m.Serialized
	}
	return nil
}

type Ack struct {
	Errors               []string `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ack) Reset()         { *m = Ack{} }
func (m *Ack) String() string { return proto.CompactTextString(m) }
func (*Ack) ProtoMessage()    {}
func (*Ack) Descriptor() ([]byte, []int) {
	return fileDescriptor_61fc82527fbe24ad, []int{6}
}

func (m *Ack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ack.Unmarshal(m, b)
}
func (m *Ack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ack.Marshal(b, m, deterministic)
}
func (m *Ack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ack.Merge(m, src)
}
func (m *Ack) XXX_Size() int {
	return xxx_messageInfo_Ack.Size(m)
}
func (m *Ack) XXX_DiscardUnknown() {
	xxx_messageInfo_Ack.DiscardUnknown(m)
}

var xxx_messageInfo_Ack proto.InternalMessageInfo

func (m *Ack) GetErrors() []string {
	if m != nil {
		return m.Errors
	}
	return nil
}

func init() {
	proto.RegisterType((*Certificate)(nil), "ptypes.Certificate")
	proto.RegisterType((*CertificateAck)(nil), "ptypes.CertificateAck")
	proto.RegisterType((*JoinRequest)(nil), "ptypes.JoinRequest")
	proto.RegisterType((*JoinResponse)(nil), "ptypes.JoinResponse")
	proto.RegisterType((*Message)(nil), "ptypes.Message")
	proto.RegisterType((*Packet)(nil), "ptypes.Packet")
	proto.RegisterType((*Ack)(nil), "ptypes.Ack")
}

func init() {
	proto.RegisterFile("overlay.proto", fileDescriptor_61fc82527fbe24ad)
}

var fileDescriptor_61fc82527fbe24ad = []byte{
	// 359 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xc1, 0x6a, 0xdb, 0x40,
	0x10, 0x95, 0x6a, 0x5b, 0xc2, 0x23, 0xd7, 0x2d, 0x53, 0x63, 0x8c, 0xa0, 0xa5, 0xec, 0x49, 0xed,
	0x41, 0x14, 0x9b, 0xb6, 0xe4, 0x90, 0x83, 0x31, 0xe4, 0x10, 0x08, 0x09, 0xf2, 0x2d, 0xb7, 0x8d,
	0x34, 0x4e, 0x84, 0x64, 0xaf, 0xb2, 0xbb, 0x76, 0x70, 0xbe, 0x3d, 0x87, 0x20, 0xad, 0x94, 0x28,
	0x8e, 0x73, 0xd3, 0x7b, 0x9a, 0xf7, 0x78, 0x6f, 0x66, 0xe1, 0xb3, 0xd8, 0x91, 0xcc, 0xf9, 0x3e,
	0x2c, 0xa4, 0xd0, 0x02, 0x9d, 0x42, 0xef, 0x0b, 0x52, 0xec, 0x14, 0xbc, 0x05, 0x49, 0x9d, 0xae,
	0xd2, 0x98, 0x6b, 0xc2, 0x09, 0xb8, 0x3c, 0x49, 0x24, 0x29, 0x35, 0xb1, 0x7f, 0xda, 0xc1, 0x20,
	0x6a, 0x20, 0x8e, 0xa0, 0xb7, 0xe3, 0xf9, 0x96, 0x26, 0x9f, 0x2a, 0xde, 0x00, 0xf6, 0x15, 0x86,
	0x2d, 0xf9, 0x3c, 0xce, 0xd8, 0x35, 0x78, 0xe7, 0x22, 0xdd, 0x44, 0x74, 0xbf, 0x25, 0xa5, 0x4b,
	0x99, 0x16, 0x19, 0x6d, 0x2a, 0xbb, 0x7e, 0x64, 0x00, 0xfe, 0x05, 0x2f, 0x7e, 0x95, 0x55, 0x96,
	0xde, 0xf4, 0x5b, 0x68, 0x32, 0x85, 0x2d, 0xc7, 0xa8, 0x3d, 0xc7, 0x4e, 0x60, 0x60, 0xbc, 0x55,
	0x21, 0x36, 0x8a, 0xf0, 0x17, 0xf4, 0x0a, 0x22, 0x59, 0x66, 0xed, 0x7c, 0x64, 0x60, 0x26, 0xd8,
	0x7f, 0x70, 0x2f, 0x48, 0x29, 0x7e, 0x4b, 0x88, 0xd0, 0x5d, 0x49, 0xb1, 0xae, 0x0b, 0x56, 0xdf,
	0x65, 0xef, 0x82, 0xef, 0x73, 0xc1, 0x93, 0xba, 0x5f, 0x03, 0x59, 0x00, 0xce, 0x15, 0x8f, 0x33,
	0xd2, 0xf8, 0x03, 0x40, 0x91, 0x4c, 0x79, 0x9e, 0x3e, 0x52, 0x52, 0xab, 0x5b, 0x0c, 0xfb, 0x0e,
	0x9d, 0x79, 0x9c, 0xe1, 0x18, 0x1c, 0x92, 0x52, 0xd4, 0xa9, 0xfa, 0x51, 0x8d, 0xa6, 0x4f, 0x36,
	0xb8, 0x97, 0xe6, 0x06, 0x38, 0x83, 0x6e, 0x59, 0x04, 0x5f, 0x12, 0xb7, 0x56, 0xe6, 0x8f, 0xde,
	0x92, 0xa6, 0x2b, 0xb3, 0xf0, 0x1f, 0xf4, 0x96, 0x77, 0x5c, 0x12, 0x1e, 0xeb, 0xe9, 0x8f, 0x8f,
	0x90, 0xe5, 0x3d, 0x2c, 0xfc, 0x0d, 0xdd, 0x05, 0xcf, 0x73, 0xfc, 0xd2, 0x4c, 0xd4, 0x8b, 0xf0,
	0x0f, 0x09, 0x66, 0x61, 0x08, 0xce, 0x52, 0x4b, 0xe2, 0x6b, 0x1c, 0x36, 0x3f, 0x4d, 0x7b, 0xff,
	0x00, 0x33, 0x2b, 0xb0, 0xff, 0xd8, 0x18, 0x80, 0x7b, 0x26, 0xe4, 0x03, 0x97, 0xc9, 0x3b, 0x81,
	0xd7, 0xe0, 0x2a, 0xc5, 0x8d, 0x53, 0xbd, 0xbb, 0xd9, 0x73, 0x00, 0x00, 0x00, 0xff, 0xff, 0x73,
	0xfb, 0x8b, 0x12, 0x88, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OverlayClient is the client API for Overlay service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OverlayClient interface {
	// Join handles join request from an unknown node. It accepts to share the
	// certificates if the token is valid.
	Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error)
	// Share handles a certificate share from another participant of the
	// network.
	Share(ctx context.Context, in *Certificate, opts ...grpc.CallOption) (*CertificateAck, error)
	Call(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
	Stream(ctx context.Context, opts ...grpc.CallOption) (Overlay_StreamClient, error)
	Forward(ctx context.Context, in *Packet, opts ...grpc.CallOption) (*Ack, error)
}

type overlayClient struct {
	cc grpc.ClientConnInterface
}

func NewOverlayClient(cc grpc.ClientConnInterface) OverlayClient {
	return &overlayClient{cc}
}

func (c *overlayClient) Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error) {
	out := new(JoinResponse)
	err := c.cc.Invoke(ctx, "/ptypes.Overlay/Join", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *overlayClient) Share(ctx context.Context, in *Certificate, opts ...grpc.CallOption) (*CertificateAck, error) {
	out := new(CertificateAck)
	err := c.cc.Invoke(ctx, "/ptypes.Overlay/Share", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *overlayClient) Call(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/ptypes.Overlay/Call", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *overlayClient) Stream(ctx context.Context, opts ...grpc.CallOption) (Overlay_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Overlay_serviceDesc.Streams[0], "/ptypes.Overlay/Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &overlayStreamClient{stream}
	return x, nil
}

type Overlay_StreamClient interface {
	Send(*Packet) error
	Recv() (*Packet, error)
	grpc.ClientStream
}

type overlayStreamClient struct {
	grpc.ClientStream
}

func (x *overlayStreamClient) Send(m *Packet) error {
	return x.ClientStream.SendMsg(m)
}

func (x *overlayStreamClient) Recv() (*Packet, error) {
	m := new(Packet)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *overlayClient) Forward(ctx context.Context, in *Packet, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, "/ptypes.Overlay/Forward", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OverlayServer is the server API for Overlay service.
type OverlayServer interface {
	// Join handles join request from an unknown node. It accepts to share the
	// certificates if the token is valid.
	Join(context.Context, *JoinRequest) (*JoinResponse, error)
	// Share handles a certificate share from another participant of the
	// network.
	Share(context.Context, *Certificate) (*CertificateAck, error)
	Call(context.Context, *Message) (*Message, error)
	Stream(Overlay_StreamServer) error
	Forward(context.Context, *Packet) (*Ack, error)
}

// UnimplementedOverlayServer can be embedded to have forward compatible implementations.
type UnimplementedOverlayServer struct {
}

func (*UnimplementedOverlayServer) Join(ctx context.Context, req *JoinRequest) (*JoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Join not implemented")
}
func (*UnimplementedOverlayServer) Share(ctx context.Context, req *Certificate) (*CertificateAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Share not implemented")
}
func (*UnimplementedOverlayServer) Call(ctx context.Context, req *Message) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Call not implemented")
}
func (*UnimplementedOverlayServer) Stream(srv Overlay_StreamServer) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}
func (*UnimplementedOverlayServer) Forward(ctx context.Context, req *Packet) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Forward not implemented")
}

func RegisterOverlayServer(s *grpc.Server, srv OverlayServer) {
	s.RegisterService(&_Overlay_serviceDesc, srv)
}

func _Overlay_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OverlayServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ptypes.Overlay/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OverlayServer).Join(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Overlay_Share_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Certificate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OverlayServer).Share(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ptypes.Overlay/Share",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OverlayServer).Share(ctx, req.(*Certificate))
	}
	return interceptor(ctx, in, info, handler)
}

func _Overlay_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OverlayServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ptypes.Overlay/Call",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OverlayServer).Call(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _Overlay_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OverlayServer).Stream(&overlayStreamServer{stream})
}

type Overlay_StreamServer interface {
	Send(*Packet) error
	Recv() (*Packet, error)
	grpc.ServerStream
}

type overlayStreamServer struct {
	grpc.ServerStream
}

func (x *overlayStreamServer) Send(m *Packet) error {
	return x.ServerStream.SendMsg(m)
}

func (x *overlayStreamServer) Recv() (*Packet, error) {
	m := new(Packet)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Overlay_Forward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Packet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OverlayServer).Forward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ptypes.Overlay/Forward",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OverlayServer).Forward(ctx, req.(*Packet))
	}
	return interceptor(ctx, in, info, handler)
}

var _Overlay_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ptypes.Overlay",
	HandlerType: (*OverlayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Join",
			Handler:    _Overlay_Join_Handler,
		},
		{
			MethodName: "Share",
			Handler:    _Overlay_Share_Handler,
		},
		{
			MethodName: "Call",
			Handler:    _Overlay_Call_Handler,
		},
		{
			MethodName: "Forward",
			Handler:    _Overlay_Forward_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _Overlay_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "overlay.proto",
}
