// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package roster

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Roster is a list of participants each having an address and a public key.
type Roster struct {
	Addresses            [][]byte   `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	PublicKeys           []*any.Any `protobuf:"bytes,2,rep,name=publicKeys,proto3" json:"publicKeys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Roster) Reset()         { *m = Roster{} }
func (m *Roster) String() string { return proto.CompactTextString(m) }
func (*Roster) ProtoMessage()    {}
func (*Roster) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *Roster) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Roster.Unmarshal(m, b)
}
func (m *Roster) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Roster.Marshal(b, m, deterministic)
}
func (m *Roster) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Roster.Merge(m, src)
}
func (m *Roster) XXX_Size() int {
	return xxx_messageInfo_Roster.Size(m)
}
func (m *Roster) XXX_DiscardUnknown() {
	xxx_messageInfo_Roster.DiscardUnknown(m)
}

var xxx_messageInfo_Roster proto.InternalMessageInfo

func (m *Roster) GetAddresses() [][]byte {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *Roster) GetPublicKeys() []*any.Any {
	if m != nil {
		return m.PublicKeys
	}
	return nil
}

type ChangeSet struct {
	Remove               []uint32 `protobuf:"varint,1,rep,packed,name=remove,proto3" json:"remove,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeSet) Reset()         { *m = ChangeSet{} }
func (m *ChangeSet) String() string { return proto.CompactTextString(m) }
func (*ChangeSet) ProtoMessage()    {}
func (*ChangeSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *ChangeSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeSet.Unmarshal(m, b)
}
func (m *ChangeSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeSet.Marshal(b, m, deterministic)
}
func (m *ChangeSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeSet.Merge(m, src)
}
func (m *ChangeSet) XXX_Size() int {
	return xxx_messageInfo_ChangeSet.Size(m)
}
func (m *ChangeSet) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeSet.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeSet proto.InternalMessageInfo

func (m *ChangeSet) GetRemove() []uint32 {
	if m != nil {
		return m.Remove
	}
	return nil
}

type ActionProto struct {
	Remove               []uint32 `protobuf:"varint,1,rep,packed,name=remove,proto3" json:"remove,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActionProto) Reset()         { *m = ActionProto{} }
func (m *ActionProto) String() string { return proto.CompactTextString(m) }
func (*ActionProto) ProtoMessage()    {}
func (*ActionProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2}
}

func (m *ActionProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionProto.Unmarshal(m, b)
}
func (m *ActionProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionProto.Marshal(b, m, deterministic)
}
func (m *ActionProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionProto.Merge(m, src)
}
func (m *ActionProto) XXX_Size() int {
	return xxx_messageInfo_ActionProto.Size(m)
}
func (m *ActionProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionProto.DiscardUnknown(m)
}

var xxx_messageInfo_ActionProto proto.InternalMessageInfo

func (m *ActionProto) GetRemove() []uint32 {
	if m != nil {
		return m.Remove
	}
	return nil
}

func init() {
	proto.RegisterType((*Roster)(nil), "roster.Roster")
	proto.RegisterType((*ChangeSet)(nil), "roster.ChangeSet")
	proto.RegisterType((*ActionProto)(nil), "roster.ActionProto")
}

func init() {
	proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5)
}

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 182 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2b, 0xca, 0x2f, 0x2e,
	0x49, 0x2d, 0x92, 0x92, 0x4c, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x8b, 0x26, 0x95, 0xa6,
	0xe9, 0x27, 0xe6, 0x55, 0x42, 0x94, 0x28, 0xc5, 0x70, 0xb1, 0x05, 0x81, 0x15, 0x09, 0xc9, 0x70,
	0x71, 0x26, 0xa6, 0xa4, 0x14, 0xa5, 0x16, 0x17, 0xa7, 0x16, 0x4b, 0x30, 0x2a, 0x30, 0x6b, 0xf0,
	0x04, 0x21, 0x04, 0x84, 0x4c, 0xb8, 0xb8, 0x0a, 0x4a, 0x93, 0x72, 0x32, 0x93, 0xbd, 0x53, 0x2b,
	0x8b, 0x25, 0x98, 0x14, 0x98, 0x35, 0xb8, 0x8d, 0x44, 0xf4, 0x20, 0xe6, 0xea, 0xc1, 0xcc, 0xd5,
	0x73, 0xcc, 0xab, 0x0c, 0x42, 0x52, 0xa7, 0xa4, 0xcc, 0xc5, 0xe9, 0x9c, 0x91, 0x98, 0x97, 0x9e,
	0x1a, 0x9c, 0x5a, 0x22, 0x24, 0xc6, 0xc5, 0x56, 0x94, 0x9a, 0x9b, 0x5f, 0x96, 0x0a, 0x36, 0x9d,
	0x37, 0x08, 0xca, 0x53, 0x52, 0xe5, 0xe2, 0x76, 0x4c, 0x2e, 0xc9, 0xcc, 0xcf, 0x0b, 0x00, 0x3b,
	0x1a, 0x87, 0xb2, 0x24, 0x36, 0xb0, 0x2d, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x39, 0x8d,
	0x6d, 0x15, 0xe5, 0x00, 0x00, 0x00,
}
