// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package roster

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Roster is a list of participants each having an address and a public key.
type Roster struct {
	Addresses            [][]byte   `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	PublicKeys           []*any.Any `protobuf:"bytes,2,rep,name=publicKeys,proto3" json:"publicKeys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Roster) Reset()         { *m = Roster{} }
func (m *Roster) String() string { return proto.CompactTextString(m) }
func (*Roster) ProtoMessage()    {}
func (*Roster) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *Roster) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Roster.Unmarshal(m, b)
}
func (m *Roster) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Roster.Marshal(b, m, deterministic)
}
func (m *Roster) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Roster.Merge(m, src)
}
func (m *Roster) XXX_Size() int {
	return xxx_messageInfo_Roster.Size(m)
}
func (m *Roster) XXX_DiscardUnknown() {
	xxx_messageInfo_Roster.DiscardUnknown(m)
}

var xxx_messageInfo_Roster proto.InternalMessageInfo

func (m *Roster) GetAddresses() [][]byte {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *Roster) GetPublicKeys() []*any.Any {
	if m != nil {
		return m.PublicKeys
	}
	return nil
}

// Task is the message for a client task.
type Task struct {
	Remove               []uint32 `protobuf:"varint,1,rep,packed,name=remove,proto3" json:"remove,omitempty"`
	Addr                 []byte   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	PublicKey            *any.Any `protobuf:"bytes,3,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetRemove() []uint32 {
	if m != nil {
		return m.Remove
	}
	return nil
}

func (m *Task) GetAddr() []byte {
	if m != nil {
		return m.Addr
	}
	return nil
}

func (m *Task) GetPublicKey() *any.Any {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func init() {
	proto.RegisterType((*Roster)(nil), "roster.Roster")
	proto.RegisterType((*Task)(nil), "roster.Task")
}

func init() {
	proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5)
}

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2b, 0xca, 0x2f, 0x2e,
	0x49, 0x2d, 0x92, 0x92, 0x4c, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x8b, 0x26, 0x95, 0xa6,
	0xe9, 0x27, 0xe6, 0x55, 0x42, 0x94, 0x28, 0xc5, 0x70, 0xb1, 0x05, 0x81, 0x15, 0x09, 0xc9, 0x70,
	0x71, 0x26, 0xa6, 0xa4, 0x14, 0xa5, 0x16, 0x17, 0xa7, 0x16, 0x4b, 0x30, 0x2a, 0x30, 0x6b, 0xf0,
	0x04, 0x21, 0x04, 0x84, 0x4c, 0xb8, 0xb8, 0x0a, 0x4a, 0x93, 0x72, 0x32, 0x93, 0xbd, 0x53, 0x2b,
	0x8b, 0x25, 0x98, 0x14, 0x98, 0x35, 0xb8, 0x8d, 0x44, 0xf4, 0x20, 0xe6, 0xea, 0xc1, 0xcc, 0xd5,
	0x73, 0xcc, 0xab, 0x0c, 0x42, 0x52, 0xa7, 0x94, 0xc6, 0xc5, 0x12, 0x92, 0x58, 0x9c, 0x2d, 0x24,
	0xc6, 0xc5, 0x56, 0x94, 0x9a, 0x9b, 0x5f, 0x96, 0x0a, 0x36, 0x98, 0x37, 0x08, 0xca, 0x13, 0x12,
	0xe2, 0x62, 0x01, 0x59, 0x21, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x13, 0x04, 0x66, 0x0b, 0x19, 0x71,
	0x71, 0xc2, 0x4d, 0x90, 0x60, 0x56, 0x60, 0xc4, 0x69, 0x11, 0x42, 0x59, 0x12, 0x1b, 0x58, 0xc2,
	0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xcb, 0x51, 0x33, 0x22, 0x01, 0x01, 0x00, 0x00,
}
